# Volcado

Al finalizar el exámen y entregarlo, este se escanea y se guarda en un sobre cerrado que queda fuera de la disposición del candidato.

Hasta la convocatoria 2025 no se ha facilitado nunca a los candidatos una copia escaneada del exámen, aunque el candidato y el tribunal sí dispondrán de esa copia durante la defensa.

Puesto que pueden transcurrir varios meses desde el fin de las preguntas.

Es conveniente que el candidato realice un volcado del exámen nada más acabarlo, que consiste en copiar todo lo escrito y nos acordamos al momento pues el material que hemos aportado es la base para la siguiente prueba, que es la defensa.

Consejos sobre la realización del volcado:

- No leer o hablar con otros compañeros hasta no estar seguros de haber terminado el volcado personal, para evitar contaminarlo.
- No contrastar la información con fuentes externas hasta no haber terminado el volcado, para evitar contaminarlo.
- Reservar entre 3-4 horas para realizar el volcado.
- Postergarlo lo menos posible después del exámen.
- Se puede emplear grabaciones de audio y su posterior transcripción automática para la parte práctica.
