# Lectura

La lectura, habitualmente conocido como la defensa, es la exposición oral en sesión pública ante el tribunal calificador de las dos partes del ejercicio.

Es una prueba individual. Van llamando a los candidatos por orden alfabético de los apellidos empezando a contar desde la letra obtenida por sorteo y que figura en las bases.

Tras la lectura del ejercicio por el candidato, se procede a preguntas del tribunal hasta un máximo de 30 minutos.

Pueden pasar pocas o muchas semanas entre el supuesto práctico y la defensa, dependiendo del orden en el que aparezca el candidato.

En la promoción 2023, las lecturas de promoción interna llevaron 4 semanas y las de ingreso libre llevaron 15 semanas (4 meses), aunque en la memoria del Tribunal figura que fueron 20.

## Descripción de la lectura

La prueba comienza con la lectura en alto del exámen por el candidato. Mientras el Tribunal escucha, además ellos disponen de una pantalla en la que ven el exámen original.

Le siguen un máximo de 30 minutos de preguntas formuladas por el Tribunal.

En las bases de la convocatoria de 2025 se indica lo siguiente:

> El ejercicio deberá ser leído íntegramente por la persona aspirante en sesión pública ante el tribunal. Una vez leído el ejercicio completo, el tribunal procederá a realizar cuantas preguntas considere necesarias durante un período máximo de treinta minutos, para determinar el grado de adecuación de la solución propuesta, para lo cual se podrá disponer de los elementos de apoyo que considere pertinentes, y el nivel de conocimientos de la persona aspirante sobre las materias incluidas en el programa que figura en el anexo II.

## Preparación de la lectura

La defensa se puede preparar individualmente, en una academia, con un preparador o con un grupo de estudio.

Conviene ensayar la defensa con otros candidatos o preparadores, y también con una IA.

Se puede asistir a defensas de cualquier candidato, por lo que conviene asistir a la de otros candidatos que vayan antes. Compartir las preguntas que se van encontrando.

Es conveniente que el candidato desarrolle una plantilla de posibles preguntas que se puede hacer sobre el exámen. Esta se puede realizar en base a los comentarios recibidos durante los ensayos de las defensas y las defensas de otros candidatos.

Conviene conocer quién forma parte del Tribunal e intentar reforzar los conocimientos asociados a cada uno de los candidatos, para anticipar posibles preguntas.

Se deben revisar los temas tratados en el supuesto práctico y análisis pormenorizado.

## Asistencia como público a las lecturas

Las lecturas son en sesión pública, por lo que cualquier persona puede asistir público. No obstante, el aforo a las mismas es limitado, por lo que puede convenir asistir con antelación.

Algunos grupos de candidatos o voluntarios, como Preparatic, recopilan las preguntas que formula el Tribunal a los candidatos. Conviene recopilar las preguntas que realiza el Tribunal y estudiar y ensayar su posible respuesta.

## Ensayo de la lectura

Es recomendable grabarse y visualizar, para detectar puntos de mejora.

También ensayar las defensas y posibles preguntas con otros candidatos, profesores o preparadores.

Se deben ensayar todos aquellos puntos que se detallan como consejos en la ejecución de la defensa.

## Realización de la lectura de la lectura

Al Tribunal se le habla de usted, y se suele usar la fórmula "con permiso del Tribunal, se procede a la lectura del ejercicio" al empezar a leer la defensa.

Se recomienda sostener los papeles con ambas manos para mantener una postura erguida y facilitar el mantener un contacto visual con el Tribunal.

Tratar de modular la voz para evitar una lectura monótona y hacer pausas. Para descansar o hacer un inciso entre partes del exámen se puede aprovechar el beber agua.

Tratar de no reaccionar visiblemente en caso de encontrar discrepancias entre lo escrito en el exámen y el volcado.

Algunas preguntas pueden ir enfocadas sobre errores que se hayan cometido en el ejercicio, y dan una segunda oportunidad.

## Puntuación de la lectura

La puntuación final de las lecturas se registra al finalizar cada sesión de lecturas, y no recibe ninguna revisión posterior.

Según se puede comprobar en el [informe del Tribunal de la convocatoria 2013](https://sede.inap.gob.es/sites/sede/files/public/2026-03/260211nformeFinal_OEP2023_v6_signed_JHUMGDGZPN_154AB89SD658.pdf), no parece que haya una relación clara entre la semana presentada y la nota obtenida.
