# Adjudicación

En este apartado se detalla la fase final de adjudicación, en la que se realiza la oferta, elección y adjudicación de destino y el nombramiento como funcionario en el CSSTIAE.

Hitos y subfases de la fase de adjudicación:

- Elección de destinos
- Nombramiento como funcionario de carrera
- Toma de posesión

Los anuncios sobre la fase de adjudicación no se realizan en la web de INAP, ya que se considera que las fases dependientes de esta institución (oposición, concurso-oposición y selección) han finalizado.

En su lugar, los anuncios relacionados con la fase de adjudicación se realizan directamente en el portal del MTDFP, dentro de la [sección "Convocatorias para el ingreso a Cuerpos/Escalas Generales de la Administración General del Estado"](https://digital.gob.es/funcion-publica/dgfp/acceso-empleo-publico/convocatorias-personal-funcionario/generales){target="_blank"}, buscando el enlace al cuerpo CSSTIAE y la convocatoria correspondiente (...-2025).

El enlace a la convocatoria concreta no se crea hasta que no se realice el nombramiento de funcionario en prácticas para esa convocatoria, por lo que en un inicio es necesario acceder a través del índice general de cuerpos y convocatorias de los cuerpos/escalas generales de la AGE.
