# Aprendizaje

La primera fase del curso se conoce como aprendizaje competencial básico.
2. Transferencia competencial al puesto

Curso de selección o curso selectivo.

## Descripción del curso selectivo

El curso selectivo consta de 2 semanas en modo presencial y 2 semanas en formato online.

La parte del curso en modo presencial tiene lugar en la sede del INAP, en Madrid.

Al finalizar el curso selectivo se recibe una calificación. Es necesario obtener al menos la mitad de la calificación máxima para superar el curso de selección.

## Anuncios del curso selectivo

Los anuncios relacionados con la fase de selección no se realizan en la entrada del CSSTIAE en el área de "Procesos selectivos", sino en la del área de "Cursos selectivos".

Se puede acceder a la entrada del CSSTIAE de "Cursos selectivos" de las siguientes formas:

- Desde el [portal del INAP](https://www.inap.es), yendo a "Selección" > "Cursos selectivos" >> "Curso Selectivo del Cuerpo Superior de Sistemas y Tecnologías de la Información de la Administración del Estado".
- Directamente desde el enlace <https://www.inap.es/es/seleccion/cursos-selectivos/curso-selectivo-del-cuerpo-superior-de-sistemas-y-tecnologias-de-la-informacion-de-la-administracion-del-estado>.

En un inicio se publica solamente una nota informativa sobre el inicio del curso selectivo. Posteriormente, se publica una nota más detallada sobre el curso selectivo.
