project:
  type: book
  output-dir: _book

book:
  title: "Guía CSSTIAE 2025"
  subtitle: "Manual de preparación para opositores"
  author: "Pablo Gallardo"
  date: today
  language: es
  favicon: images/favicon.png
  
  site-url: https://pmgallardo.github.io/guia-csstiae-2025/
  repo-url: https://github.com/pmgallardo/guia-csstiae-2025
  repo-actions: [edit, issue, source]

  sidebar:
    style: "docked"
    search: true
    
  chapters:
    - index.qmd
    - part: "Inicio"
      chapters:
      - 01-inicio/index.qmd
    - part: "Ejercicio de test"
      chapters:
      - 02-test/index.qmd
    - part: "Ejercicio práctico"
      chapters:
        - 03-practico/00-gen/index.qmd
        - 03-practico/01-supuesto/index.qmd
        - 03-practico/02-analisis/index.qmd
        - 03-practico/03-volcado/index.qmd
        - 03-practico/04-lectura/index.qmd
    - part: "Ejercicio de inglés"
      chapters:
      - 04-ingles/index.qmd
    - part: "Selección"
      chapters:
      - 05-seleccion/index.qmd
    - part: "Elección"
      chapters:
      - 06-eleccion/index.qmd


    #     - 00-practico/temas.qmd
    #     - 00-practico/material.qmd
    # - part: "Supuesto práctico"
    #   chapters:
    #     - 01-supuesto/index.qmd
    #     - 01-supuesto/modelado.qmd
    #     - 01-supuesto/infr-comunes.qmd
    #     - 01-supuesto/serv-comunes.qmd
    #     - 01-supuesto/seguridad.qmd
    #     - 01-supuesto/interoperabilidad.qmd
    #     - 01-supuesto/dimensionamiento.qmd
    #     - 01-supuesto/costes.qmd
    #     - 01-supuesto/contratacion.qmd
    # - part: "Análisis pormenorizado"
    #   chapters:
    #     - 02-analisis/index.qmd
    #     - 02-analisis/organismos.qmd
    #     - 02-analisis/regulaciones.qmd
    #     - 02-analisis/estrategias.qmd
    #     - 02-analisis/iniciativas.qmd
    #     - 02-analisis/estadisticas.qmd
    #     - 02-analisis/transversales.qmd
    #     - 02-analisis/especificas.qmd
    # - part: "Volcado"
    #   chapters:
    #     - 03-volcado/index.qmd
    # - part: "Lectura"
    #   chapters:
    #     - 04-lectura/index.qmd

lang: es

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
  pdf:
    documentclass: scrreprt
    number-sections: true
    toc: true
