project:
  type: book
  output-dir: _book

book:
  title: "Guía CSSTIAE 2025"
  subtitle: "Manual de preparación para opositores"
  author: "Pablo Gallardo"
  date: today
  language: es
  favicon: images/favicon.png
  
  site-url: https://pmgallardo.github.io/guia-csstiae-2025/
  repo-url: https://github.com/pmgallardo/guia-csstiae-2025
  repo-actions: [edit, issue, source]

  sidebar:
    style: "docked"
    search: true
    
  chapters:
    - index.qmd
    - part: "General"
      chapters:
      - 00-general/00-gen.qmd
      - 00-general/01-apoyo.qmd
    - part: "Inicio"
      chapters:
      - 01-inicio/00-gen.qmd
      - 01-inicio/01-anuncio.qmd
      - 01-inicio/02-admision.qmd
    - part: "Test"
      chapters:
      - 02-test/00-gen.qmd
    - part: "Práctico"
      chapters:
      - 03-practico/00-gen.qmd
      - 03-practico/01-supuesto.qmd
      - 03-practico/02-analisis.qmd
      - 03-practico/03-volcado.qmd
      - 03-practico/04-lectura.qmd
    - part: "Inglés"
      chapters:
      - 04-ingles/00-gen/index.qmd
      - 04-ingles/01-convalid-ingles/index.qmd
      - 04-ingles/02-ej-ingles/index.qmd
    - part: "Concurso"
      chapters:
      - 05-concurso/00-gen/index.qmd
      - 05-concurso/01-aprobados/index.qmd
      - 05-concurso/02-func-prac/index.qmd
    - part: "Selección"
      chapters:
      - 06-seleccion/00-gen.qmd
      - 06-seleccion/01-aprendizaje.qmd
      - 06-seleccion/02-transferencia.qmd
    - part: "Adjudicación"
      chapters:
      - 07-adjudicacion/00-gen.qmd
      - 07-adjudicacion/01-eleccion.qmd
      - 07-adjudicacion/02-func-carrera.qmd
      - 07-adjudicacion/03-posesion.qmd

lang: es

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
  pdf:
    documentclass: scrreprt
    number-sections: true
    toc: true
