# Fase de adjudicación

En este apartado se detalla la fase final de adjudicación, en la que se realiza la oferta, elección y adjudicación de destino y el nombramiento como funcionario en el CSSTIAE. Al igual que la fase inicial, la fase de adjudicación no está reconocida oficialmente por la AGE, sino que se trata de un criterio de agrupación conveniente ideado para la presente guía y que se corresponde con los pasos finales del proceso selectivo.

Hitos y subfases de la fase de adjudicación:

- Elección de destinos
- Nombramiento como funcionario de carrera
- Toma de posesión

Los anuncios sobre la fase de adjudicación no se realizan en la web de INAP, ya que se consideran finalizadas las fases dependientes de esta institución (oposición, concurso-oposición y selección).

En su lugar, los anuncios relacionados con la fase de adjudicación se realizan directamente en el portal del MTDFP, dentro de la [sección "Convocatorias para el ingreso a Cuerpos/Escalas Generales de la Administración General del Estado"](https://digital.gob.es/funcion-publica/dgfp/acceso-empleo-publico/convocatorias-personal-funcionario/generales){target="_blank"}, buscando el enlace al cuerpo CSSTIAE y la convocatoria correspondiente (...-2025).

El enlace a la convocatoria concreta no se crea hasta que no se realiza el nombramiento de funcionario en prácticas para esa convocatoria, por lo que en un inicio es necesario acceder a esta página través del índice general de convocatorias para el ingreso de los cuerpos/escalas generales de la AGE.
