## Estadísticas

Conviene incluir en el análisis pormenorizados algunas estadísticas relevantes. Se muestran a continuación algunas fuentes donde obtener estas estadísticas.

### Portales de estadísticas

- UE
  - DESI
  - Informes sobre el estado de la Década Digital
- España
  - INE (Instituto Nacional de Estadística) 
  - OBSAE (Observatorio de Administración Electrónica)
  - OTNSI
  - Informe REINA
  - OAW (Observatorio de Accesibilidad Web)

#### DESI

El [Índice de Economía y Sociedad Digital](https://digital-strategy.ec.europa.eu/es/policies/desi-spain) (*Digital Economy and Social Index*, DESI) realiza un ranking de los estados miembros de la Unión Europea en función de distintos aspectos relativos a la digitalización.

También se publica en la [PAe](https://administracionelectronica.gob.es/pae_Home/pae_OBSAE/Posicionamiento-Internacional/Comision_Europea_OBSAE/Indice-de-Economia-y-Sociedad-Digital-DESI-.html).

#### Informes sobre el estado de la Década Digital

[Informe de 2026](https://ec.europa.eu/commission/presscorner/detail/es/ip_26_1366)

#### INE

El Instituto Nacional de Estadística (INE) es un organismo que tiene como objetivo compartir estadísticas de interés general para España.

El INE desarrolla distintos grupos indicadores, entre ellos:

- EVGVD (Estadística de Violencia Doméstica y Violencia de Género)
- [EPA](https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176918&menu=ultiDatos&idp=1254735976595) (Encuesta de Población Activa)

#### OBSAE

El Observatorio de Administración Electrónica (OBSAE) es un portal con el objetivo de compartir información sobre la Administración Electrónica en las AAPP. Está impulsada por la AEAD.

[OBSAE](https://dataobsae.administracionelectronica.gob.es){target="_blank"}

#### OTNSI

Informes del OTNSI (Observatorio Nacional de Tecnología y Sociedad).

#### Informe REINA

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Organismos:
  - AEAP
  - Comisiones Ministeriales de Administración Digital
- Referencias:
  - [Informe REINA en PAe](https://administracionelectronica.gob.es/pae_Home/pae_OBSAE/pae_Informes/pae_InformeREINA/pae_InfDescripcion.html?idioma=eu), PAe.
:::

El informe REINA (Revisión de Equipamiento, Inversión y Nómina de Personal Informático) es elaborado anualmente bajo el impulso de la Comisión Permanente del Consejo Superior de Administración Electrónica.

#### OAW

El Observatorio de Accesibilidad Web (OAW) es...

[OAW en el PAe](https://administracionelectronica.gob.es/pae_Home/pae_Estrategias/pae_Accesibilidad/pae_Observatorio_de_Accesibilidad.html){target="_blank"}

## Indicadores

### EVGVD

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [EVGVD en el INE](https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176866&menu=ultiDatos&idp=1254735573206){target="_blank"}
:::

La Estadística de Violencia Doméstica y Violencia de Género (EVGVD) es...

### EPA

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [EPA en el INE](https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176918&menu=ultiDatos&idp=1254735976595){target="_blank"}
:::

La Encuesta de Población Activa (EPA) es...
