## Marco normativo

Por convenio, se refieren las regulaciones europeas y españolas de la siguiente manera:

| Ámbito | Cód. título | Cód. referencia | Convención URL |
| - | - | - | - |
| UE | X(UE) 2015/123 | CELEX:12345X1234 | ELI |
| ES | X 123/2000 | BOE-A-2000-12345 | ELI |

ELI (*European Legislation Identifier*) es un identificador único para la legislación europea y nacional que ha sido adoptado también por España.

Abreviaturas usadas para cada tipo de regulación, de acuerdo al ELI:

| Ámbito | Abrev. | Significado |
| - | - | - |
| UE | Reg | Reglamento |
| UE | Dir | Directiva |
| ES | LO | Ley Orgánica |
| ES | L | Ley |
| ES | RDL | Real Decreto-Ley |
| ES | RDLg | Real Decreto Legislativo |

### Marco normativo europeo

A partir de 2015 se cambió la numeración de las normativas, poniendo primero el año y después el número de la normativa.

<!-- ### Reg(UE) 910/2014. eIDAS {#CELEX:32014R0910}

:::{.callout-warning}
## 🕸️Obsoleto
eIDAS fue sustituido por eIDAS 2 en 2025.
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [R(UE) 910/2014 en EUR-Lex](https://eur-lex.europa.eu/eli/reg/2014/910/oj?locale=es)
::: -->

#### Reg(UE) 2016/679. RGPD {#CELEX:32016R0679}

R(UE) 2016/679. Reglamento General de Protección de Datos (RGPD).

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [RGPD en EUR-Lex]( http://data.europa.eu/eli/reg/2016/679/oj){target="_blank"}
  - <https://eur-lex.europa.eu/ES/legal-content/summary/general-data-protection-regulation-gdpr.html>{target="_blank"}
:::

<!-- #### Reg(UE) 2021/241. Mecanismo de Recuperación y Resiliencia (MRR) {#celex-32021R0241}

:::{.callout-warning}
## 🕸️Obsoleto
El MRR se concibió con fecha límite hasta agosto 2026.
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
    - [R(UE) 2021/241 en EUR-Lex](http://data.europa.eu/eli/reg/2021/241/oj){target="_blank"}
:::

Exige que los hitos y objetivos finales de las reformas e inversiones de los planes nacionales se hayan completado, como máximo, el 31/08/2026. -->

#### Reg(UE) 2021/694. Programa Europa Digital {#CELEX:32021R0694}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
    - [R(UE) 2021/694 en EUR-Lex](http://data.europa.eu/eli/reg/2021/694/oj?locale=es){target="_blank"}
:::

#### Reg(UE) 2022/868. Ley de Gobernanza de Datos {#CELEX:32022R0868}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [R(UE) 2022/868 en EUR-Lex](http://data.europa.eu/eli/reg/2022/868/oj?locale=es){target="_blank"}
:::

#### Reg(UE) 2023/2854. Ley de Datos {#CELEX:32023R2854}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [R(UE) 2023/2854 en EUR-Lex](http://data.europa.eu/eli/reg/2023/2854/oj?locale=es){target="_blank"}
:::

Ley de Datos (*Data Act*), regula el acceso y uso de datos generados por productos y servicios conectados, y establece normas para la portabilidad de datos y la interoperabilidad.

#### Reg(UE) 2024/903. Reglamento Europeo sobre la Interoperabilidad (REI) {#CELEX:32024R0903}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [R(UE) 2024/903 en EUR-Lex](http://data.europa.eu/eli/reg/2024/903/oj?locale=es){target="_blank"}
:::

#### Reg(EU) 2024/1183. eIDAS 2 {#CELEX:32024R1183}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [R(UE) 2024/1183 en EUR-Lex](http://data.europa.eu/eli/reg/2024/1183/oj?locale=es){target="_blank"}
:::

#### Reg(UE) 2024/1689. Ley de Inteligencia Artificial {#CELEX:32024R1689}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
Referencias
 - [R(UE) 2024/1689 en EUR-Lex](http://data.europa.eu/eli/reg/2024/1689/oj?locale=es){target="_blank"}
:::

### Marco normativo español

#### RD 4/2010. ENI {#BOE-A-2010-1331}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias:
  - [RD 4/2010 en BOE](https://www.boe.es/eli/es/rd/2010/01/08/4/con){target="_blank"}
:::

Regula el Esquema Nacional de Interoperabilidad.

Frase plantilla para el ENI:

> El sistema ha sido diseñado de acuerdo con los principios y criterios establecidos en el Esquema Nacional de Interoperabilidad, regulado en el RD 4/2010, favoreciendo la interoperabilidad organizativa, semántica y técnica, el uso de estándares aplicables y la adecuada gestión y conservación de la información durante todo su ciclo de vida.

#### L 19/2013. Transparencia, acceso a la información pública y buen gobierno {#BOE-A-2013-12887}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias:
  - [L 19/2013 en BOE](https://www.boe.es/eli/es/l/2013/12/09/19/con){target="_blank"}
:::

### RDLg 5/2015. Estatuto Básico del Empleado Público (EBEP) {#BOE-A-2015-11719}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias:
  - [RDLg 5/2015 en BOE](https://www.boe.es/eli/es/rdlg/2015/10/30/5/con)
:::

#### RD 668/2015. Acceso electrónico de los ciudadanos a los servicios públicos {#BOE-A-2015-8048}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [RD 668/2015](https://www.boe.es/eli/es/rd/2015/07/17/668){target="_blank"}
:::

Una frase plantilla que se puede añadir para el RD 668/2015:

> El sistema bajo análisis se encuentra plenamente alineado con las directrices del Real Decreto 668/2015, de acceso electrónico de los ciudadanos a los servicios públicos, garantizando los principios de accesibilidad universal, interoperabilidad y seguridad en la prestación del servicio público por medios electrónicos.

#### L 9/2017. CSP {#BOE-A-2017-12902}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
    - <https://www.boe.es/eli/es/l/2017/11/08/9/con>{target="_blank"}
:::

La ley 9/2017, de Contratación en el Sector Público (CSP) traspone las directivas 2014/23/UE, Directiva 2014/24/UE y Directiva 2014/25/UE.

El art. 1 define los principios de contratación:

- Libertad de acceso a las licitaciones.
- Publicidad y transparencia de los procedimientos.
- No discriminación e igualdad de trato entre los licitadores.

#### LO 3/2018 (LPD-GDD) {#BOE-A-2018-16673}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - <https://www.boe.es/eli/es/lo/2018/12/05/3/con>{target="_blank"}
:::

Ley Orgánica de Protección de Datos y Garantía de Derechos Digitales (LOPD-GDD) complementa el RGPD.

#### RDL 36/2020. PRTR {#BOE-A-2020-17340}

:::{.callout-warning}
## 🕸️Obsoleto
El PRTR se concibió con fecha límite hasta agosto 2026.
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - <https://www.boe.es/eli/es/lo/2018/12/05/3/con>{target="_blank"}
:::

Se detalla en el apartado [PRTR](#PRTR) de Estrategias.

#### RD 1118/2024. Estatuto de la AEAD {#BOE-A-2024-22929}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [RD 1118/2024](https://www.boe.es/eli/es/rd/2024/11/05/1118){target="_blank"}
:::
