## Temáticas transversales

En este apartado se revisan temáticas que pueden ser comunes a proyectos de distinta naturaleza.

### Relaciones con las AAPP

::: {.callout-warning icon="false" collapse="true"}
## 🥈Temática candidata N2
El vocal titular del Tribunal J. M. Daza dirige los proyectos de atención ciudadana.
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Estrategias:
  - Brújula Digital 2030. Puntos cardinal "Servicios públicos": 100% de servicios públicos digitales.
- **Regulaciones:**
  - ES:
    - L 39/2015. Procedimiento Administrativo Común AAPP (PACAP).
    - [RD 668/2015](#BOE-A-2015-8048). Acceso electrónico de los ciudadanos a los servicios públicos.
    - L 29/1999. Contencioso-administrativo.
:::

### Funcionamiento de las AAPP

::: {.callout-note icon="false"}
## 📋 Marco de referencia

- CE:
  - CE art. 103.1 (principios de buena administración)
- Regulaciones
  - ES:
    - L 40/2015. Régimen Jurídico del Sector Público (RJSP).
- Temas:
  - 8. Régimen jurídico de las AAPP. Procedimiento administrativo
:::

El art. 103.1 de la Constitución menciona los principios de buena administración:

> La Administración Pública sirve con objetividad los intereses generales y actúa de acuerdo con los **principios de eficacia, jerarquía, descentralización, desconcentración y coordinación**, con sometimiento pleno a la ley y al Derecho. 

La descentralización se refiere a la delegación de competencias entre distintas personas jurídicas (agencias, comunidades autónomas, etc.), mientras que la desconcentración se refiere a la delegación de competencias dentro de una misma persona jurídica.

### Administración digital

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Regulaciones:
  - UE
    - R (UE) 2021/694. Programa Europa Digital.
  - ES
    - [RD 1118/2024](#BOE-A-2024-22929). Estatuto de la AEAD
- Iniciativas:
  - CTT (Centro de Transferencia de Tecnología)
:::

### Interoperabilidad (análisis pormenorizado)

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Regulaciones
  - UE
    - Declaración Ministerial de Tallín sobre la administración electrónica
    - [Reg(UE) 2024/903](#CELEX:32024R0903). Reglamento Europeo sobre la Interoperabilidad (REI)
    - [Reg(UE) 910/2014](#CELEX:32024R1183). eIDAS 2
  - ES
    - RD 4/2010. Esquema Nacional de Interoperabilidad
    - L 37/2007. Reutilización de datos en Sector Público.
- ODS
  - Obj. 17. Alianza para lograr los objetivos
- Organismos
  - CTT (Centro de Transferencia de Tecnología)
  - CISE (Centro de Interoperabilidad Semántica)
- Temas
  - 45. ENI
  - 46. NTI
:::

Ver sección sobre [interoperabilidad en la AGE](../01-supuesto/index.qmd#interoperabilidad)

### Participación ciudadana

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- CE
  - CE art. 1 (Estado social y democrático; soberanía reside en el pueblo español)
  - CE art. 9 (poderes públicos prommieven la participación de los ciudadanos en la vida política, económica, cultural y social)
  - CE art. 23 (derecho de participación)
- Regulaciones
  - [L 19/2013. Transparencia, acceso a la información pública y buen gobierno](#BOE-A-2013-12887)
:::

### Transparencia

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- CE
  - Art. 105. Derecho a la información y transparencia
  - Art. 23. Participación ciudadana
- Regulaciones
  - ES
    - [L 19/2013. Transparencia, acceso a la información pública y buen gobierno](#BOE-A-2013-12887)
:::

Art. 105.b) CE: Regula el acceso de los ciudadanos a los archivos y registros administrativos (derecho a la información y transparencia).

### Accesibilidad (análisis pormenorizado)

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Regulaciones
  - UE
    - D(UE) 2016/2102. Accesibilidad de los sitios webs y aplicaciones para dispositivos móviles de los organismos del sector público
  - ES
    - RD 1494/2007. Accesibilidad a la sociedad de la información y medios
    - RD 1112/2018. Accesibilidad de los sitios web y aplicaciones para dispositivos móviles del sector público
- Organismos
  - Observatorio de Accesibilidad
- Estándares
  - EN 301 549
- Referencias
  - <https://runmodule.com/2026/12/17/accesibilidad-digital-en-el-sector-publico-en-espana/>
:::

RD 1112/2018 es la trasposición de la directiva UE 2016/2102. Requieren seguir el estándar EN 301 549, publicado en la decisión de ejecución UE 2018/2048.

### Protección de datos

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Organismos
  - Agencia Española de Protección de Datos (AEPD)
- Regulaciones
  - UE
    - **[R(UE) 2016/679. RGPD](#CELEX:32016R0679)**
  - ES
    - **[LO 3/2018. LOPD-GDD](#BOE-A-2018-16673)**
- Temas
  - 82. Adaptación LOPD
- Referencias
  - <https://runmodule.com/2026/04/14/proteccion-de-datos-personales-en-espana/>
:::

### Seguridad de la información

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- CE
  - CE art. 18 (derecho a la intimidad)
- Regulaciones
  - UE
    - NIS2
    - CRA
  - ES
    - L 6/2020, de servicios electrónicos de confianza
    - RD 43/2021, seguridad de redes y SI
    - **[RD 311/2022](#ens), Esquema Nacional de Seguridad (ENS)**
    - RDL 7/2022, seguridad 5G
- Iniciativas
  - Estrategia de Seguridad Nacional
  - Estrategia Nacional de Ciberseguridad
  - Esquema Nacional de Seguridad (ENS)
  - Guías CCN-STIC
- Temario
  - 48. ENS (incluye ENS, CCN-STIC)
- Referencias
  - <https://runmodule.com/2026/07/28/seguridad-de-la-informacion-en-el-sector-publico-en-espana/>{target="_blank"}
:::

### Identificación electrónica

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Estrategias
  - Brújula Digital 2030. Puntos cardinal "Servicios públicos": 80% de ciudadanos usan identificación digital.
- Regulaciones
  - UE
    - Reg(EU) 2024/1183. eIDAS{#CELEX:32014R0910}
:::

### Nube

::: {.callout-warning icon="false" collapse="true"}
## 🥇Temática candidata N1
La secretaria titular del Tribunal trabajó en nubeSARA entre 2018 y 2026.
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Infraestructuras
  - NubeSARA
:::

### Datos

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Estrategias
  - UE
    - [Unión de Datos](#union-datos)
- Regulaciones
  - [Reg(UE) 2022/868](#CELEX:32022R0868). Ley de Gobernanza de Datos.
  - [Reg(UE) 2023/2854](#CELEX:32023R2854). Ley de Datos.
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Regulaciones:
  - UE:

    - Reg(UE) 2023/2854. Ley de Datos (*Data Act*){#CELEX:32023R2854}
- Estrategias:
  - UE:
    - Estrategia Europea del Dato {estrategias.qmd#Estrategia-Europea-del-Dato}
:::

La Ley de Gobernanza de Datos (*Data Governance Act*, DGA) regula la reutilización de datos protegidos del sector público (como datos de salud o secretos comerciales), crea la figura de los intermediarios de datos neutros y regula el "altruismo de datos" (donar datos para el bien común).

### Inteligencia artificial

::: {.callout-warning icon="false" collapse="true"}
## 🥈Temática candidata N2
El vocal titular L. A. Hernández es profesor universitario de Inteligencia Artificial.
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Estrategias:
  - UE:
    - [Estrategia para la aplicación de la IA](#apply-ai)
- Regulaciones:
  - UE:
    - [Reglamento UE 2024/1689. Ley de Inteligencia Artificial](#CELEX:32024R1689)
- Temas:
  - 70. Inteligencia artificial
- Referencias:
  - [Inteligencia artificial](https://digital.gob.es/digitalizacion/areas-interes/inteligencia-artificial). digital.gob.es.
:::
