# Transferencia

Tras finalizar la fase de aprendizaje competencial básico tiene lugar la transferencia competencial al puesto, que consiste en un periodo de prácticas tutorizadas de 12 semanas (3 meses) de duración.

La información de este curso se publica en la [entrada del CSSTIAE de cursos selectivos](https://www.inap.es/es/seleccion/cursos-selectivos/curso-selectivo-del-cuerpo-superior-de-sistemas-y-tecnologias-de-la-informacion-de-la-administracion-del-estado), bajo el título "Convocatoria tutorización prácticas".

Al finalizar las prácticas el tutor aplica una calificación al aspirante.

Tras la finalización de la fase de transferencia, los funcionarios en prácticas continúanlas prácticas en el destino asignado hasta su nombramiento como funcionario de carrera. Pueden no continuar haciéndolas en algunos casos, como la posesión de una licencia de estudios.

El mes de agosto se considera como no lectivo, por lo que si coincide con el periodo de prácticas los funcionarios en prácticas no trabajan durante este periodo.
