## Material de preparación

### Material teórico

Se pueden consultar las siguientes fuentes de teoría:

- [Temario ofrecido por Astic](https://www.astic.es/temario-tic-a1/) (de pago)
- [Material ofrecido por Preparatic](https://www.preparatic.org/material-preparatic-31/) (gratuito)
- Material adicional facilitado por academias y preparadores

Los materiales teóricos de Astic y Preparatic están organizados en función del temario de convocatorias recientes.

De cara al ejercicio práctico conviene realizar cierta preparación de material propio para recopilar información sobre estrategias, marcos normativos, iniciativas o costes de recursos actualizados. 

### Repositorio de ejercicios prácticos

#### Ejercicios prácticos oficiales del INAP

El INAP recopila los enunciados de los ejercicios prácticos más recientes, mientras que Preparatic comparte los volcados de soluciones de algunos candidatos que voluntariamente los han compartido.

| Conv. | Prom. | Núm. ejer. | Título | Enun. | Volc. |
| - | - | - | - | - | - |
| 2023 | 30 | 2 | Diseño de un sistema para la gestión del ciclo presupuestario | [PDF](https://sede.inap.gob.es/documents/59312/2382235/Enunciadodelsegundoejercicio_COMPLETO_LIBRE_AA392H55BO_154AB89SD658.pdf/2e1f4267-3818-99e0-fe39-3a332520c67d) | [Drive](https://drive.google.com/drive/folders/1NRc1pcqt53SorUaOXAISC8i4LZ6Z068y?usp=sharing) |
| 2022 | 29 | 2 | Plataforma Digital Común | [PDF](https://sede.inap.gob.es/documents/59312/2298662/Enunciado2oEjercicioLibreGeneral_IX32FT6CLA_154AB89SD658.pdf/0316efec-0e7d-0c10-eaf1-cc2922e3ef85) | [Drive](https://drive.google.com/drive/folders/1opzfbqezX_lLTMW3ZArStot5yBq8aF-P?usp=sharing) |
| 2020 | 28 | 3 | Plataforma digital de cooperación entre administraciones públicas: Plataform@ | [PDF](https://sede.inap.gob.es/documents/59312/2061887/Supuestopractico3erejercicio2020_KJJ1YDZ8D2_154AB89SD658.pdf/739684b6-a1e7-e24e-ed7f-62a15a940c6a) | [Drive](https://drive.google.com/drive/folders/1wU9vF81krOYLLaC41XMCdQkcuZy_t7CF) |
| 2019 | 27 | 3 | Evolución de la Carpeta Ciudadana: Carpet@ | [PDF](https://sede.inap.gob.es/documents/59312/1863992/CSSTIAE+-+Tercer+Ej+-+Enunciado_154AB89SD658.pdf/2ed378ff-becb-b856-d64c-be7e3af3a5d9) | [Drive](https://drive.google.com/file/d/1UNqYCcdwlKYMMg5iNm3sIOOw9VzHPP_2/view) |
| 2018 | 26 | 3 | Espacio de Participación Ciudadana del Gobierno de España (ESPACE) | [PDF](https://sede.inap.gob.es/documents/59312/1763823/2019-09-14Ejercicio3_154AB89SD658.pdf/f9356500-8822-56f1-e4a3-ea20effb71b1) | - |
| 2017 | 25 | 3 | Descripción del sistema de gestión de crisis consulares | [PDF](https://www.baquedano.es/TIC_ejer_3_AGE_2018.pdf) |
| 2016 | 24 | 4 | SELECCION@ | [PDF](https://www.baquedano.es/TIC_4_ejer_libre_promo_AGE_2017.pdf) | - |
| 2015 | 23 | 4 | Sistema de Información y Seguimiento sobre Incendios Forestales (SISIF) | - | - |
| 2014 | 22 | 4 | Plan de Administración Digital de la CNPI | [PDF](https://www.inap.es/es/documents/10136/1698123/TICA1Ejercicio4_154AB89SD658.pdf/ab357be5-0792-012b-9735-8416b4641ad1) | - |
| 2012-2013 | 21 | 4 | Sistema integrado de información y seguimiento del PEFJ | [PDF](https://www.inap.es/es/documents/10136/1698123/Cuarto_ejercicio%202013.pdf/40b87770-ba50-25b1-e2b9-160bc28999a7) | - |
| 2011 | 20 | 4 | Particip@Web | [PDF](https://www.inap.es/es/documents/10136/1698123/Cuarto_ejercicio%202011.pdf/d897c040-84e2-70a4-434c-63a9da73bd8f) | - |

#### Ejercicios prácticos de otras AAPP

Los ejercicios prácticos de procesos de selección de contenido similar al CSSTIAE y fuera de la AGE pueden emplearse para ensayar.

#### Ejercicios prácticos no oficiales

Adicionalmente, algunas academias y preparadores desarrollan sus propios enunciados y comparten las propuestas de solución de los candidatos.
