## Toma de posesión en destino

La toma de posesión formaliza el acceso al puesto de trabajo y otorga la condición de funcionario de carrera, al ser este el último requisito.

El plazo para tomar posesión es de 15 días hábiles a partir del inicio del periodo fijado en la resolución de nombramiento, o de un mes si la toma de posesión implica un cambio de residencia o un desplazamiento de larga distancia.

Es aconsejabe contactar con el área de Recursos Humanos del destino asignado para acordar la fecha y los detalles sobre la toma de posesión. En muchos casos, será el propio área la que se ponga en contacto previamente con el aspirante aprobado.

En el acto de la toma de posesión se deberán firmar diversos documentos, entre ellos la promesa o juramento de acatamiento a la Constitución y de lealtad al Rey, así como la declaración de incompatibilidades.

El documento F2R, titulado "Resolución de toma de posesión en puesto de trabajo" acredita la toma de posesión. Se pueden encontrar al cabo de varios días en el portal Funciona, en Expediente > Notificaciones, y teóricamente también en la Carpeta Ciudadana.
