# Anuncio

Cada nueva convocatoria del proceso de selección de ingreso al CSSTIAE se anuncia oficialmente a través del BOE.

Adicionalmente, las convocatorias son informadas a través de las siguientes vías alternativas:

- Apertura de nueva convocatoria en la [plataforma IPS](https://ips.redsara.es).
- Apertura de nueva convocatoria en la [sección del CSSTIAE en la web del INAP](https://www.inap.es/en/seleccion/procesos-selectivos-de-cuerposescalas-generales/cuerpo-superior-de-sistemas-y-tecnologias-de-la-informacion-de-la-administracion-del-estado).
- Anuncio en el [canal "Preparatic" de Telegram](https://t.me/s/preparatic) (no oficial).

Se deben leer cuidadosamente las bases y comprobar que se cumplen todos requisitos, incluyendo los de formación o de situación administrativa. También conviene revisar las fechas límites, especialmente para el siguiente paso, el de inscripción.

En caso de que el aspirante se haya presentado más veces a la convocatoria, conviene revisar si ha habido cambios reseñables entre las convocatorias anteriores y la actual y no dar por hecho lo aplicado en ocasiones anteriores.