# Inscripción

## Inscripción

La inscripción se realiza a través del portal Inscripción de Pruebas Selectivas (IPS) de la AGE.

Consejos de inscripción:

- Vigilar la fecha límite. No apurar a las últimas fechas para hacer la inscripción, para evitar que algún contratiempo impida participar en la convocatoria.
- Antes de que finalice el proceso de inscripción, tratar de obtener uno de los títulos de inglés convalidables para ahorrarse la realización de un ejercicio y contar con la tranquilidad y certeza de poder darlo por superado.
- Ante la duda de no saber si se va a poder preparar el ejercicio lo mejor es inscribirse igualmente, puesto que pasan meses entre la inscripción y la realización primer ejercicio y da tiempo a que cambie la situación, y el desembolso por inscripción no es excesivamente caro.

## Admisión y subsanación

Tras la inscripción, se publica una lista provisional de admitidos y excluidos al proceso selectivo. Cada aspirante debe confirmar que aparece en la lista provisional de admitidos.

En caso de figurar en la lista provisional de excluidos, se deben seguir las instrucciones de subsanación.

Tras atenderse todas las subsanaciones, se publican las listas definitivas de incluidos y excluidos.