# Inicio

Este apartado se detallan los primeros pasos relacionados con las pruebas selectivas de ingreso al CSSTIAE, incluyendo el anuncio de la convocatoria y la inscripción.

## Estructura de las pruebas selectivas

El proceso de las pruebas selectivas es complejo, largo (dilatándose más de dos años) y varía entre convocatorias, por lo que se require cierto estudio para alcanzar su comprensión.

### Vías de acceso a las pruebas selectivas

Existen dos vías de acceso dentro de una convocatoria:

- Ingreso libre (IL) (también llamado en ocasiones acceso libre): accesible para todos los aspirantes, funcionarios de carrera o no, que cumplan ciertas condiciones.
- Promoción interna (PI): accesible solamente por funcionarios de carrera que cumplan ciertas condiciones.

El proceso para los aspirantes de IL y PI comparte aspectos comunes pero también algunas particularidades. Por ejemplo, el número de plazas disponibles son distintas para cada vía.

Los aspirantes solo pueden presentarse por una de las dos vías.

### General y cupo

Los aspirantes pueden escoger acceder por la vía general o por cupo.

### Fases de las pruebas selectivas

En la convocatoria de 2025, el proceso de selección consta de las siguientes fases:

1. Inscripción
2. Oposición
  1. Ejercicio de test
  2. Ejercicio práctico
  3. Ejercicio de inglés
3. Concurso *(solo PI)*
4. Curso selectivo
  1. Aprendizaje básico
  2. Transferencia competencial al puesto
6. Elección de destinos
7. Nombramiento como funcionario de carrera
8. Toma de posesión

Cada una de estas fases se explicará con más detalle en cada uno de sus apartados.

Existen ciertas restricciones temporales en el proceso, de acuerdo al art. 108.2 del RDL 6/2023:

- La fase de oposición (desde la realización del primer ejercicio hasta la publicación de la relación definitiva de aprobados) no puede exceder el año.
- El proceso de selección completo no puede exceder los 2 años desde su publicación en el BOE (hasta el nombramiento como funcionario de carrera).

Los meses de agosto se declaran inhábiles, por lo que no se cuentan estos meses de cara a cumplir plazos.

En cualquier caso, no hay que olvidar que los plazos indicados se pueden incumplir si hay causas justificadas, por lo que estas restricciones son límites orientativos.

### Cronograma de las pruebas selectivas

Cronograma de pruebas selectivas de la convocatoria 2025:

| Hito | Fecha |
| - | - |
| Anuncio de convocatoria | 18/12/25 |
| Inicio inscripción| 19/12/25 |
| Límite inscripción | 20/01/26 |
| Realización ej. test | 16/07/26 |
| Relación def. aprobados test | - |
| Realización ej. prác. | > 15/09/26 |
| Fin lecturas ej. prác. PI | < 15/11/26 |
| Realización ej. inglés PI | > 15/11/26 |
| Relación def. aprobados ej. inglés PI | - |
| Fin lecturas ej. prác. IL | < 15/03/27 |
| Valoración prov. méritos PI | - |
| Valoración def. méritos PI | - |
| Realización ej. inglés IL | > 15/03/27 |
| Publicación calif. def. prác. | > 15/03/27 |
| Relación prov. aspirantes aprobados | - |
| Relación def. aspirantes aprobados | < 01/08/27 |
| Nombramiento como funcionario en prácticas | - |
| Inicio aprendizaje | - |
| Fin aprendizaje | - |
| Inicio transferencia | - |
| Fin transferencia | - |
| Nombramiento como funcionario de carrera | < 18/02/27 |
| Inicios elección destinos | - |
| Fin elección destinos | - |
| Inicio toma de posesión | - |

Para la convocatoria 2023, la precedente, el cronograma fue:

| Hito | Fecha |
| - | - |
| Anuncio de convocatoria | 24/07/24 |
| Inicio inscripción| 29/07/24 |
| Límite inscripción | 26/08/24 |
| Realización ej. test | 14/02/25 |
| Relación def. aprobados test | 26/03/25 |
| Realización ej. prác. | 09/05/25 |
| Realización ej. inglés PI | 18/07/25 |
| Relación def. aprobados ej. inglés PI | 28/07/25 |
| Fin lecturas ej. prác. IL | 20/10/25 |
| Valoración prov. méritos PI | 07/11/25 |
| Realización ej. inglés IL | 21/11/25 |
| Valoración def. méritos PI | 05/12/25 |
| Relación def. aprobados ej. inglés IL | 27/11/25 |
| Relación prov. aspirantes aprobados | 19/01/26 |
| Relación def. aspirantes aprobados | 11/03/26 |
| Nombramiento como funcionario en prácticas | 01/04/26 |
| Inicio aprendizaje | 09/04/26 |
| Fin aprendizaje | 08/05/26 |
| Inicio transferencia | 11/05/2026 |
| Fin transferencia | 30/07/2025 |
| Nombramiento como funcionario de carrera | < 24/09/2026 |
| Inicio elección destinos | - |
| Fin elección destinos | - |
| Inicio toma de posesión | - |

## Anuncio de convocatoria

Cada nueva convocatoria del proceso de selección de ingreso al CSSTIAE se anuncia oficialmente a través del BOE.

Adicionalmente, las convocatorias son informadas a través de las siguientes vías alternativas:

- Apertura de nueva convocatoria en la [plataforma IPS](https://ips.redsara.es).
- Apertura de nueva convocatoria en la [sección del CSSTIAE en la web del INAP](https://www.inap.es/en/seleccion/procesos-selectivos-de-cuerposescalas-generales/cuerpo-superior-de-sistemas-y-tecnologias-de-la-informacion-de-la-administracion-del-estado).
- Anuncio en el [canal "Preparatic" de Telegram](https://t.me/s/preparatic) (no oficial).

Se deben leer cuidadosamente las bases y comprobar que se cumplen todos requisitos, incluyendo los de formación o de situación administrativa. También conviene revisar las fechas límites, especialmente para el siguiente paso, el de inscripción.

En caso de que el aspirante se haya presentado más veces a la convocatoria, conviene revisar si ha habido cambios reseñables entre las convocatorias anteriores y la actual y no dar por hecho lo aplicado en ocasiones anteriores.

## Inscripción

La inscripción se realiza a través del portal Inscripción de Pruebas Selectivas (IPS) de la AGE.

Consejos de inscripción:

- Vigilar la fecha límite. No apurar a las últimas fechas para hacer la inscripción, para evitar que algún contratiempo impida participar en la convocatoria.
- Antes de que finalice el proceso de inscripción, tratar de obtener uno de los títulos de inglés convalidables para ahorrarse la realización de un ejercicio y contar con la tranquilidad y certeza de poder darlo por superado.
- Ante la duda de no saber si se va a poder preparar el ejercicio lo mejor es inscribirse igualmente, puesto que pasan meses entre la inscripción y la realización primer ejercicio y da tiempo a que cambie la situación, y el desembolso por inscripción no es excesivamente caro.

## Admisión y subsanación

Tras la inscripción, se publica una lista provisional de admitidos y excluidos al proceso selectivo. Cada aspirante debe confirmar que aparece en la lista provisional de admitidos.

En caso de figurar en la lista provisional de excluidos, se deben seguir las instrucciones de subsanación.

Tras atenderse todas las subsanaciones, se publican las listas definitivas de incluidos y excluidos.

## Becas para opositores

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias:
  - [](https://www.inap.es/es/becas-y-ayudas/becas-para-opositores)
  - [](https://sede.inap.gob.es/es/procedimientos-y-servicios/becas-y-ayudas/becas-para-opositores)
:::

El INAP publica becas para opositores de sus procesos de selección. Las bases reguladores y convocatorias se pueden encontrar en en enlace <https://sede.inap.gob.es/es/procedimientos-y-servicios/becas-y-ayudas/becas-para-opositores>.

La beca cubriría costes relacionados con la preparación del proceso de selección, incluyendo la inscripción en academias o cursos de preparadores.

La última convocatoria de becas fue en 2013.
