## Infraestructuras comunes

### RedSARA

RedSARA (Sistemas de Aplicaciones y Redes para las administraciones)

### sTESTA

sTESTA es una red transeuropea que incluye a las instituciones públicas europeas y de los estados europeos. RedSARA enlaza con la red sTESTA.

### Servicio Unificado de Telecomunicaciones

### Servicio de alojamiento de infraestructuras TIC

### Nube (supuesto práctico)

Ventajas y desventajas del uso de la nube.

En caso de optar por la nube, se puede proponer el uso de NubeSARA, una nube pública exclusiva para el ámbito de las AAPP.

#### NubeSARA {#nubesara}

::: {.callout-warning icon="false" collapse="true"}
## 🥇Temática candidata N1
La secretaria suplente del Tribunal trabajó en nubeSARA entre 2018 y 2026.
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - [NubeSARA](https://administracionelectronica.gob.es/ctt/verPestanaGeneral.htm?idIniciativa=nubesara), PAe.
:::

NubeSARA es un servicio de nube híbrida para la AGE, gestionado desde la AEAD. Los organismos del sector público tienen esta infraestructura disponible desde la Red SARA.

NubeSARA se lleva a cabo en una serie de CPDs disponibles. Hay 3 CPDs: Moncloa (el histórico), El Escorial (empleado sobre todo por las Fuerzas de Seguridad) y Las Rozas (en desarrollo).

Cumplen el Tier IV.

### Servicio de seguridad gestionada
