## Seguridad

La seguridad es una cuestión presente en todos los ejercicios prácticos recientes de la AGE. Estaría presente a lo largo de los siguientes apartados:

- ENS
- Protección de datos personales

### Esquema Nacional de Seguridad (ENS)

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2023.2, 2022.2, 2020.2, 2019.3, 2018.2
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Regulación:
  - [RD 311/2022](02-analisis.qmd#BOE-A-2022-7191). ENS
- Guías:
  - [CCN-STIC 803. Valorización de los sistemas en el ENS](https://www.ccn-cert.cni.es/ccn-cert/documentos/guias-ccn-stic/ccn-stic-803.html){target="_blank"}
- Temas:
  - 48. ENS
:::

El Esquema Nacional de Seguridad (ENS) es una pregunta permanente en los ejercicios prácticas del CSSTIAE, ya sea por mención expresa o necesidad de considerarla en los diseños. Se suele preguntar expresamente a través de la categorización del sistema y los mecanismos de seguridad aplicables.

Las **categorías de seguridad del ENS** son:

- Básica
- Media
- Alta

Las **dimensiones de seguridad del ENS** son:

1. Confidencialidad
2. Integridad
3. Disponibilidad
4. Autenticidad
5. Trazabilidad

Se asigna a cada dimensión de seguridad una de las categorías. La más alta categoría obtenida en todas las dimensiones determina la categoría global del sistema.

A la hora de evaluar los ejercicios, se debe vigilar cuándo poner categoría alta, pues está reservada a sistemas de información que manejan datos de especial sensibilidad, como los relacionados con la seguridad nacional, la defensa, la seguridad pública y la salud pública.

También se debe vigilar cuándo poner categoría básica, pues está reservada a sistemas de información que manejan datos de baja sensibilidad, como los relacionados con la publicidad, la meteorología o la cultura. Un sistema que almacena datos personales no puede tener categoria básica.

Como referencia sobre cómo categorizar la seguridad del ENS, se puede mencionar la guía CCN-STIC 803 "Valorización de los sistemas en el ENS".

Las **medidas de seguridad del ENS** se detallan en el anexo II del RD 311/2022. Se dividen en tres grupos:

- Marco organizativo (org)
- Marco operacional (op)
- Medidas de protección (mp)

El listado de mecanismos del ENS es el siguiente:

- Marco organizativo (org)
  - Política de seguridad
  - Normativa de seguridad
  - Procedimientos de seguridad
  - Proceso de autorización
- Marco operacional (op)
  - op.pl. Planificación
    - Análisis de riesgos
    - Arquitectura de Seguridad
    - Adquisición de nuevos componentes
    - Dimensionamiento/gestión de la capacidad
    - Componentes certificados *(n.a. básica)*
  - op.acc. Control de acceso
    - op.acc.1. **Identificación**
    - op.acc.2. Requisitos de acceso
    - op.acc.3. Segregación de funciones y tareas *(n.a. básica)*
    - op.acc.4. Proceso de gestión de derechos de acceso
    - op.acc.5. Mecanismo de autenticación (usuarios externos)	
    - op.acc.6. Mecanismo de autenticación (usuarios de la organización)
  - op.exp. Explotación
    - **Inventario de activos**
    - Configuración de seguridad
    - Gestión de la configuración de seguridad
    -	Mantenimiento y actualizaciones de seguridad
    -	Gestión de cambios *(n.a. básica)*
    -	Protección frente a código dañino
    -	Gestión de incidentes
    - Registro de la actividad
    -	Registro de la gestión de incidentes
    - Protección de claves criptográficas
  - op.ext. Recursos externos
      - Contratación y acuerdos de nivel de servicio *(n.a. básica)*
      - Gestión diaria *(n.a. básica)*
      - Protección de la cadena de suministro *(n.a. básica y alta)*
      - Interconexión de sistemas *(n.a. básica)*
  - op.nub. Servicios en la nube
    - Protección de servicios en la nube
  - op.cont. Continuidad del servicio
    - **Análisis de impacto** *(n.a. básica)*
    - Plan de continuidad *(n.a. básica y media)*
    - Pruebas periódicas *(n.a. básica y media)*
    - Medios alternativos *(n.a. básica y media)*
  - op.mon. Monitorización del sistema
    - **Detección de intrusión**
    - Sistemas de métricas
    - Vigilancia
- Medidas de protección (mp)
  - mp.if. Protección de las instalaciones e infraestructuras
    - Áras separadas y con control de acceso
    - Identificación de las personas
    - Acondicionamiento de los locales
    - Energía eléctrica
    - Protección frente a incendios
    - Protección frente a inundaciones
    - Registro de entrada y salida de equipamiento
  - mp.per. Gestión del personal
    - Caracterización del puesto de trabajo
    - Deberes y obligaciones
    - Concienciación
    - Formación
  - mp.eq. Protección de los equipos
    - Puesto de trabajo despejado
    - Bloqueo de puesto de trabajo *(n.a. básica)*
    - Protección de dispositivos portátiles
    - Otros dispositivos conectados a la red
  - mp.com. Protección de las comunicaciones
    - Perímetro seguro
    - Protección de la confidencialidad
    - Protección de la integridad y de la autenticidad
    - Separación de flujos de información en la red *(n.a. básica)*
  - mp.si. Protección de los soportes de información
    - Marcado de soportes *(n.a. básica)*
    - Criptografía *(n.a. básica)*
    - Custodia
    - Transporte
    - Borrado y destrucción
  - mp.sw. Protección de las aplicaciones informáticas
    - Desarrollo de aplicaciones *(n.a. básica)*
    - **Aceptación y puesta en servicio**
  - mp.info. Protección de la información
    1. Datos personales
    2. Calificación de la información *(n.a. básica)*
    3. Firma electrónica
    4. Sellos de tiempo *(n.a. básica y media)*
    5. Limpieza de documentos
    6. Copias de seguridad
  - mp.s. Protección de los servicios
    1. Protección del correo electrónico
    2. Protección de servicios y aplicaciones web
    3. Protección de la navegación web
    4. Protección frente a denegación de servicio *(n.a. básica)*

Medidas para mecanismos:

| Mecanismos | Descripción | B | M | Medidas |
| - | - | - | - | - |
| op.mon.3 | Vigilancia | ✓ | ✓ | SAT-inet |
| mp.com.4 | **Separación flujos** | ✗ | ✓ | VLANs |

### Protección de datos personales

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2019.6, 2018.5
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Regulación:
  - EU:
    - [RGPD](02-analisis#CELEX:32016R0679)
  - ES:
    - [LO 3/2018](02-analisis#BOE-A-2018-16673). LOPD-GDD.
- Temas:
    - 82. Adaptación LOPD
:::

Obtener consentimiento del tratamiento de datos.

La Evaluación de Impacto en la Protección de Datos (EIPD) se 

### Certificados electrónicos (supuesto práctico)

### Autenticación

La autenticación en el sistema se puede realizar mediante distintos medios, cuyo uso se debe valorar dependiendo del sistema del enunciado:

- Usuario y contraseña
- Biometría
- DNI Electrónico
- Cl@ve
- Cl@ve Firma
- Autentica: solo válido para empleados de la AGE.

Además, se debe valorar el emplear métodos de autenticación de dos factores (2FA) o multifactor (MFA).

#### Biometría

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2019.6
:::

### Gestión de riesgos

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Temas
  - 47. Análisis y gestión de riesgos
:::

Este apartado trata sobre la evaluación de riesgos en proyectos de sistemas de la información.

### Guías CCN-STIC

Las guías CCN-STIC son un conjunto de documentos que proporcionan recomendaciones y buenas prácticas en materia de seguridad de la información. Estas guías están desarrolladas por el Centro Criptológico Nacional (CCN) y están dirigidas a las Administraciones Públicas y a las entidades que manejan información sensible.

Las guías suelen tratar aspectos específicos de la valoración o configuración de seguridad en el sistema. Se valora que en el ejercicio se mencionen las guías con su código. Estas guías se mencionan en este documento en cada apartado en los que vienen siendo relevantes.
