## Arquitectura lógica

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2023.1, 2022.1, 2020.1, 2019.3, 2018.1
:::

La **arquitectura lógica**, también referida en algunos ejercicios como **modelo lógico** o **arquitectura de sistema** (en singular), representa las distintas capas que posee el sistema.

La arquitectura lógica suele incluir:

  - Actores
  - Dispositivos de usuario (portátil, móvil, etc.)
  - Sistemas externos
  - API gateway
  - Estilos y patrones de arquitectura de software
  - Servidores virtuales (con su función)

Por el contrario, suelen excluir:

  - Elementos de red (redes, enrutadores, cortafuegos, etc.)
  - Elementos duplicados para obtener alta disponibilidad (HA)

 como seguridad, interoperabilidad, orquestación o accesibilidad.

A menudo los candidatos incluyen bloques transversales, incluyendo algunos como:

- Seguridad
- Interoperabilidad
- Accesibilidad
- Administración
  - Orquestación
  - Monitorización

Un **API gateway** (pasarela API) es un bloque que se encuentra entre los dispositivos de usuario y el servidor de presentación, y que se encarga de gestionar las solicitudes de los usuarios hacia las APIs del sistema.

Una aplicación de móvil se conecta directamente con el backend, ya que es la app instalada en el móvil quien lleva la carga del frontend.

Habitualmente en sector público se usa la integración de lado de servidor (*server-side integration*). Esto se hace a través de un *front-end UI composer*.

Se puede usar una CDN a la parte que sea más común a todos los usuarios, como contenido estático (una noticia, etc.).

### Estilo y patrón de arquitectura de software

La arquitectura lógica presentada debe reflejar el estilo y patrón de arquitectura empleado en 

Estilos y patrones de arquitectura de software que pueden aparecer en arquitecturas lógicas:

- Monolítico
- Multicapa
  - Modelo-vista-controlador (MVC)
  - Arquitectura hexagonal
  - Arquitectura clean
- Orientado a servicios (SOA)
  - Microservicios

##### MVC {.unnumbered .unlisted}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - <https://runmodule.com/2024/12/03/mvc-architecture/>
:::

En el modelo-vista-controlador (MVC) existiría una capa de presentación, otra de aplicación o negocio y una última de datos.

Se suelen representar la base de datos, el directorio y el gestor documental para almacenar datos.

Propuesta de niveles principales:

- Presentación
- Lógica de negocio
- Acceso a datos y servicios

##### Arquitectura hexagonal {.unnumbered .unlisted}

Considera tres capas:

- Aplicación
- Adaptadores
- Sistemas externos

La capa de aplicación contiene la lógica propia del dominio. Excluye cualquier referencia a interfaces, tecnologías o sistemas externos. 

La capa de adaptadores sirve de adaptación entre los sistemas externos y la aplicación. En el borde exterior de esta capa se encuentran los puertos, que son interfaces abstractas entre los sistemas externos y la aplicación. Los adaptadores son implementaciones de estos puertos.

Una de las particularidades de esta arquitectura es que considera a las bases de datos actores, ya que se considera dependiente de tecnología, intercambiable y por tanto externa al dominio.

Los puertos y adaptadores pueden ser primarios y secundarios. Los adaptadores primarios son los que permiten a los actores o sistemas externos interactuar con la aplicación, mientras que los adaptadores secundarios son los que permiten a la aplicación interactuar con actos externos.

La capa de sistemas externos considera los actores y sistemas fuera del control del sistema gestionado.

En la arquitectura lógica debería representarse cada adaptador entre la aplicación como un recuadro distinto.

##### Arquitectura clean {.unnumbered .unlisted}

Evolución de la arquitectura hexagonal.

##### Microservicios {.unnumbered .unlisted}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias:
  - <https://runmodule.com/2024/12/03/microservices/>
:::

En microservicios se suele pintar un API gateway al inicio de la lógica de negocio.

El API gateway son el punto de entrada a los microservicios. Puede contenter una API separada para la web, que podría ser reactiva (diseño), y una de móvil.

En la arquitectura de microservicios es obligatorio colocar un broker de mensajes o bus de eventos transversal junto a todos los microservicios, y dar a entender que la comunicación entre ellos se realiza a través de este módulo.

## Arquitecturas de sistemas

Durante el supuesto práctico se puede requerir al aspirante que proponga distintos tipos de arquitectura para un sistema de información, que se detallan en este apartado.

### Dominios/subdominios funcionales

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2023.1
:::

La identificación de dominios/subdominios funcionales se refiere a dividir el sistema en grandes áreas funcionales, agrupando las funciones que persiguen un mismo objetivo de negocio.

### Arquitectura conceptual

En la arquitectura conceptual se pueden agrupar las acciones a realizar de manera pública por un lado, las acciones del área por otro, y añadir un proceso pasarela que sea autenticación de usuario y que conecte ambos grupos.

### Arquitectura de sistemas

La arquitectura de sistemas (en plural) se refiere a un diagrama de alto nivel sobre la interacción de distintos sistemas.

### Arquitectura física

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2023.2, 2020.4, 2019.3, 2018.2
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias:
  - <https://runmodule.com/2027/03/30/network-architecture/>
:::

La arquitectura física implica especificar los componentes técnicos a emplear, ya sean físicos o virtuales.

Elementos que deben considerarse en la arquitectura física:

- Servidores físicos (bare-metal)
- Clústeres
- Almacenamiento
- Elementos de red
- Bases de datos
- Proveedores cloud

Elementos que se suelen excluir:

- Arquitectura de software

Para las bases de datos se debe elegir entre bases de datos relacionales o bases de datos NoSQL.

Se suele usar datos NoSQL cuando el volumen es alto y se busca escalabilidad horizontal (BBDD de columna ancha), cuando se busca flexibilidad estructural respecto a tablas (BBDD documental, BBDD de grafos) o se requiere simplicidad y rapidez (BBDD clave-valor).

| Tipo de BBDD | Producto código abierto | Escenario óptimo |
| - | - | - |
| Relacional | PostgreSQL | Consultas complejas |
| Columna ancha | Cassandra | Volumen alto, escalabilidad horizontal |
| Documental | FerretDB 2 + DocumentDB de Linux Foundation (compatible con MongoDB) | Datos semiestructurados |
| Grafos | Neo4j | Datos centrados en relaciones |
| Clave-valor | Valkey | Simplicidad y rapidez |

Se propone Valkey en lugar de Redis ya que el primero es un fork del segundo que mantiene la licencia permisiva original y cuenta con el soporte de la Linux Foundation.

### Arquitectura de red

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Guía CCN-STIC 811 Interconexión en el ENS
- Guía CCN-STIC 823 de utilización de servicios en la nube
- Guía CCN-STIC 408 de seguridad perimetral (cortafuegos)
- Guía CCN-STIC-836 – Seguridad en Redes Privadas Virtuales
- <https://runmodule.com/2027/03/30/network-architecture/>
:::

Una **arquitectura de red** o **red de comunicaciones** suele incluir los siguientes elementos:

- Enrutadores (*router*)
- Cortafuegos
- WAF
- Balanceadores
- Switches
- Proxy (*forward proxy*)
- Proxy inverso (*reverse proxy*)
- Redes de área local (LAN)
- VPNs
- DNS
- CDN
- Conexión con otras redes (redSARA, sTESTA)
- VLAN

Hay varias arquitecturas de red privada posibles, y una bastante habitual es la del **cortafuegos dual**. Esta consiste en segmentar la red privadas en dos:

- Red perimetral, en ocasiones llamada subred apantallada o zona desmilitarizada (*demilitarized zone*, DMZ), expuesta a una red externa a través de un cortafuegos externo o perimetral y que alberga a los servidores públicos.
- Red privada, expuesta a la red perimetral a través de un cortafuegos interno, y que aloja servidores y equipos privados.

A la hora de aplicar VLANs, una posible segmentación sería:

- Servidores de presentación
- Pasarelas / Middleware

El **enrutador** (*router*) coloca en la parte más externa de la red perimetral para conectarse con otras redes, ya sea internet o intranets como red SARA. Se empleará un enrutador distinto para cada red conectada. Además, por seguridad que requiere que los enrutadores estén duplicados.

Algunos aspirantes sustituyen el enrutador hacia la red SARA por un elemento llamado Acceso de Conexión (AC).

Los enrutadores suelen ser los últimos elementos que pertenecen a la red del organismo de la AGE gestionado.

Se coloca por tanto un **cortafuegos** (*firewall*) detrás de cada enrutador da acceso a la red privada. Los cortafuegos se colocan en pares con característicias y configuración idéntica para asegurar que si falla uno el otro se encuentra disponible. No obstante, se suele recomendar que el interno y el externo sean de fabricantes distintos, para asegurar en caso de que uno de ellos tenga una vulnerabilidad explotable que no sea posible acceder a la red apantallada.

Los candidatos suelen configurar el par de cortafuegos externo como activo-pasivo y el par de cortafuegos interno como activo-activo.

Varios enrutadores pueden emplear un mismo cortafuegos si este tiene libres interfaces de red o soporta VLANs. Los aspirantes habitualmente utilizan el mismo cortafuegos interno para conectar tanto el enrutador a las intranets como la red privada.

El cortafuegos externo tendrá una conexión directa con el cortafuegos interno.

Cada cortafuegos (o par de cortafuegos) suelen ir acompañados de un IPS o un IDS. Algunos aspirantes colocan un IDS con el cortafuegos externo y un IPS con el cortafuegos interno. Otros aspirantes colocan un único IPS en mitad de la connexión entre el cortafuegos externo y el interno. El IPS es mencionado como elemento necesario en el ENS.

La **VPN** debe estar disponible en caso de que haya usuarios que deban acceder a la red interna a través de la VPN. Se debe adaptar al [mp.com.2] del ENS. Para sistemas de categoría media estas VPN deberán utilizar algoritmos y parámetros
autorizados por el CCN (refuerzo R1). Si se trata de sistemas de categoría alta, además, se debe utilizar un dispositivo hardware certificado para el establecimiento y utilización de la VPN (refuerzos R2 y R3).

El cortafuegos interno, como se comentó, estará conectado a otras intranets (como red SARA) y a la subred apantallada.

Se representan como nubes las WLANs como red SARA y otras intranets:

- La red sTESTA se suele representar como otra nube conectada a SARA, ya que la conexión con sTESTA a través de la red SARA.
- Las redes de comunidades autónomas (CCAA) se conectan con la red SARA, nunca directamente al organismo de la AGE.
- Las redes de entidades locales (EELL) siempre están conectadas a redes de comunidades autónomas (CCAA), nunca se conectan directamente a red SARA.

Los servicios comunes y transversales de las AAPP se ofrecen a través de la red SARA.

En la red perimetral, conectados directamente con el cortafuegos exterior, suelen estar presentes:

- Sonda SAT-inet
- VLAN 10: tráfico entrante
  - Servidores de proxy inverso
  - Balanceadores
  - Servidor DNS
- VLAN acceso externo:
  - Servidores VPN
- VLAN tráfico saliente:
  - Servidores proxy
- VLAN presentación:
  - Servidores de presentación / web
- VLAN middleware:
  - API Gateway

La **sonda SAT-inet** (acrónimo de Sistema de Alerta Temprana de Internet) es un elemento de monitorización que permite al CCN monitorizar la red del organismo de la AGE.

La sonda SAT-inet se suele colocar en la red perimetral, conectada fuera de banda (*out-of-band*) a un puerto SPAN o Mirror del switch core o del cortafuegos, de manera que reciba una copia del tráfico para analizarlo de forma paralela. Es importante recalcar que NO corta el tráfico.

Referencias:

- [Sistema de Alerta Temprana (SAT-INET)](https://www.ccn-cert.cni.es/es/documentos-publicos/1306-sat-de-internet/file.html). CCN-CERT.

El **balanceador** puede software o *appliance*.

Referencias:

- CCN-STIC-140 Anexo F.88: Balanceadores de carga

Según el ENS, se debe aplicar sobre los sistemas de categoría media el refuerzo R1 "segmentación lógica básica", que implica la configuración de VLANs. Las VLANs mínimas a considerar son "Usuarios", "Servicios" y "Administración".

Sobre los sistemas de categoría alta se debe aplicar el refuerzo R2 "segmentación lógica avanzada" por VPN o el R3 "segmentación física" con segmentos físicos separados, y el R4 "puntos de interconexión".

En la **VLAN middleware** se instalan elementos como el API gateway o FIRe.

En la red privada se suelen colocar:

- Usuarios
  - Equipos personales
- Servicios
  - Servidores de aplicación
  - Servidores de documentos
  - Servicios de directorio
  - Bases de datos
- Administración
  - Servidores de monitorización
  - Servidores de integración (CI/CD)

Los aspirantes suelen definir una VLAN en la red privada por cada una de estas categorías para asegurar la segmentación de red y aumentar la seguridad. Los servidores de aplicación y las bases de datos se suelen poner por separado.

En caso de requerirse trabajar con firma electrónica, es recomendable reflejar la instalación de un **servidor local FIRe** en una VLAN de integración, ya que los servidores de aplicación estos necesitan comunicarse con la API de FIRe para enviarle el documento original y recuperar el resultado firmado.

El servidor FIRe se ubicaría dentro de la la red privada, y requeriría conectividad de salida hacia la intranet administrativa (Red SARA) para acceder a servicios transversales como @firma o Cl@ve Firma.

#### Arquitectura de red con nube híbrida

En caso de manejar de contratar un tentant en NubeSARA, los elementos de red del organismos serían los mismos pero deberían ir enmarcados con línea discontinúa que indique que se trata de un tentant de NubeSARA.
