## Tecnología

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2023.2, 2022.2, 2020.2, 2019.3, 2018.2
:::

El supuesto práctico suele incluir un apartado en el que se pregunta sobre las tecnologías tecnologías a emplear en el sistema. Se puede refererir a ella como **tecnologías**, **solución tecnológica** o **implementación tecnológica**.

La propuesta tecnológica debe ir debidamente justificada, amparada por su asentamiento en la industria o en la AGE o por su adecuación. Emplear tecnologías habituales en la AGE puede demostrar al Tribunal familiaridad e interés del aspirante por la institución y además valoración de la reutilización de conocimientos y personal ya existente.

Se debe considerar que en el sector público se suele priorizar la madurez y la estabilidad y esto se debe reflejar en la selección de tecnologías. No obstante, es posible que para cierto tipo de sistemas más innovadores sea adecuado escoger una tecnología menos habitual o más puntera.

Algunas fuentes para consultar el uso de tecnologías concretas en la AGE:

- El [Observatorio de la Administración Electrónica (OBSAE)](https://dataobsae.administracionelectronica.gob.es).
- Pliegos de licitaciones

### Tecnologías según contexto

#### Lenguajes de programación

El lenguaje de programación más empleado en la AGE para servidores back-end y aplicaciones de escritorio (este último en declive) es Java.

Para servidor front-end, TypeScript (con el framework Angular) seguido por JavaScript (con el framework React) son los lenguajes más empleados.

.NET también tiene una presencia importante en la AGE.

#### Tecnología web front-end

La tecnología web front-end más empleada en la AGE es Angular, que emplea el lenguaje de programación TypeScript. Se usa para aplicación grandes.

A cierta distancia, la segunda tecnología más utilizada es React, que emplea el lenguaje de programación JavaScript. Se usa para aplicaciones híbridas y con interfaz cambiante y muy interactivos.

Bootstap se usa también de manera minoritaria para aplicaciones web o móvil con interfaz sencilla.

#### Tecnología web back-end

El framework Spring Framework, o su alternativa Spring Boot, que emplea el lenguaje de programación Java, es el estándar en la AGE.

#### Aplicaciones de escritorio

Antes de proponer una aplicación de escritorio en el supuesto práctico se debe reflexionar, pues la tendencia actual en la AGE es priorizar aplicaciones web sobre software de escritorio tradicional. Por ello, para proponer una aplicación de escritorio se debe justificar por la necesidad de una fuerte integración con el sistema operativo o hardware (ej.: lector de tarjetas), la necesidad de un rendimiento muy alto o la necesidad de una interfaz muy compleja.

Las aplicaciones de escritorio con tecnologías **.NET**, del entorno de desarrollo de Microsoft y escritas en **C#**, son también populares en la AGE.

La AGE ha empleado históricamente **Java** con la biblioteca UI **Swing** para aplicaciones desarrolladas exclusivamente para escritorio, como por ejemplo AutoFirma. No obstante, proponerlo para una nueva aplicación puede considerarse una mala práctica al considerarse tecnología obsoleta.

Un enfoque alternativo y moderno es adaptar una aplicación web como aplicación de escritorio empleando tecnologías web híbridas empleando el framework **Angular** (o React, como opción alternativa) sobre el framework web **Electron**; Tauri sería también técnicamente válida como ventana de navegación interna (webview), pero es más experimental y no está tan extendido en la AGE.

#### Aplicaciones de móvil

Se puede consultar las tecnologías de las aplicaciones móviles en el [inventario de aplicaciones móviles del OBSAE](https://administracionelectronica.gob.es/pae_Home/eu/pae_Estrategias/pae_Movilidad_Inicio/catalogo_apps_age.html?comentarioContenido=0&idioma=es).

Se concluye leyendo este informe que las aplicaciones móviles de la AGE están realizadas principalmente con Ionic, Angular y Flutter, en orden descendente.

**Ionic** proporciona componentes específicos para móvil adaptados a cada SO y se basa en un WebView, es decir, una web inscrustada en una app de móvil. Puede combinarse con Angular u otro framework web o ejecutarse independientemente.

**Angular** es una buena opción si es necesaria una misma app para web y móvil. Es conveniente que esta web sea responsiva (se adapta a la pantalla con fluidez) o adaptativa (considera distintas configuraciones y escoge la más adecuada), lo cual se consigue con frameworks CSS como Bootstrap o Tailwind CSS.

Para la solución basadas en WebView (como Angular y Ionic), se puede emplear **Capacitor** (el reemplazo de Apache Cordova) como puente entre el dispositivo móvil y la ventana de navegación interna (WebView) en la que se ejecuta la app web de Angular. Proporciona acceso al hardware y permite al usuario mostrar la aplicación como una app.

**Flutter** ejecuta código nativo en lugar de estar basado en tecnologías web (como Angular e Ionic), lo que le da mayor rendimiento.

#### Bases de datos

Las bases de datos más empleadas en la AGE son Oracle Database (propietaria) y PostgreSQL (de código abierto).

En caso de trabajarse en de un ecosistema de Microsoft, se debe considerar Microsoft SQL Server.

#### Contenedores y orquestación

La AGE emplea habitualmente Docker para empaquetado y Kubernetes o soluciones empresariales como Red Hat OpenShift para gestionar de forma segura los clústeres en los centros de datos del Estado.

#### Mensajería e integración

Para mensajería e integración en la AGE se emplen herramientas de código abierto como RabbitMQ o Apache Kafka.

RabbitMQ se emplea más en mensajería tradicional y arquitecturas monolíticas, mientras que Apache Kafka se emplea más en big data y arquitecturas de microservicios.

#### API manager

Una opción propietaria de API manager (o gestor de APIs) habitual en la AGE es **MuleSoft AnyPoint Platform**.

Entre las opciones de código abierto que ofrecen un API manager completo se encuentra **WSO2 API Manager**.

### API gateway

La funcionalidad de API gateway (o pasarela de APIs) está habitualmente incluida en las suites de API manager. Por ello, si el sistema ya cuenta con un API manager, no es necesario implementar un API gateway adicional.

Por ejemplo, MuleSoft AnyPoint Plaform incluye MuleSoft API Gateway, mientras que WSO2 API Manager incluye WSO2 API Gateway.

Una opción de código abierto centrada en la funcionalidad de API gateway es **Kong API Gateway** Community Edition (CE). El API manager completo Kong Manager sería de pago.

### Stack de tecnologías

 Se conoce como stack a la combinación de combinación de tecnologías empleada en un sistema. A la hora de proponer el stack en el supuesto práctico, se debe reflexionar cuál es el más adecuado en base a distintos criterios.
 
 Hay combinaciones de tecnologías encontradas con más **frecuencia** que otras. Por ejemplo, es habitual encontrar Angular para el front y Spring Boot para el backend, mientras que es menos habitual encontrar Angular para el front y .NET para el backend. Puesto que se busca un sistema maduro y estable, conviene sugerir un stack habitual.

Otro criterio importante es la elección de **stacks ya habituales en la AGE**, con la ventaja de contar con familiaridad en la institución y el facilitar la búsqueda de perfiles relacionados.

A continuación se proponen tres ecosistemas o stacks de tecnologías habituales:

- Pro-Oracle
- Pro-Microsoft
- Pro-código abierto

#### Pro-Oracle

Stack genérico empleando tecnologías propias del ecosistema Oracle:

- Framework frontend: Angular (TypeScript)
- Servidor web: Oracle HTTP Server
- Framework backend: Spring Boot (Java)
- Servidor aplicación: Oracle Weblogic
- Base de datos: Oracle Database

Angular no es nativo del ecosistema Java o pro-Oracle, pero está bien integrado en él y suele ser una opción habitual. Oracle JET sería el framework frontend nativo de Oracle, pero este no es tan popular en la AGE como Angular.

Una alternativa también común en la AGE a Oracle Weblogic es IBM WebSphere, ambos propietarios.

#### Pro-Microsoft

El ecosistema pro-Microsoft tiene cierta presencia en la AGE, si bien no es ubicua.

Sugerencia de stack genérico empleando tecnologías propias del ecosistema Microsoft:

- Framework frontend: ASP.NET (C#)
- Servidor web / aplicación: IIS (Windows Server)
- Framework backend : .NET
- Framework escritorio: WPF
- Framework móvil: .NET MAUI
- Base de datos: Microsoft Server SQL

Como alternativa más moderna al framework frontend se puede usar Blazor, que permite crear aplicaciones web interactivas con C#. No obstante, de momento Blazor es poco popular en la AGE respecto a ASP.NET, pero sobre todo respecto a Angular o React.

Se propone Windows Presentation Foundation (WPF) como framework de escritorio, con la nota de que la tendencia actual de la AGE es ofrecer interfaces web en lugar de aplicaciones de escritorio. La tecnología Windows Forms (WinForms) está presente en la AGE como legacy, y no sería adecuada para nuevos sistemas.

Se propone .NET MAUI (sucesor de Xamarin) como framework de aplicaciones móviles del ecosistema pro-Microsoft, si bien no es usado habitualmente en la AGE.

#### Pro-código abierto

Propoponer un stack de código abierto otorga la ventaja de evitar costes de licenciamiento (reduciendo costes y poder agilizar los plazos de contratación) y eliminar la dependencia del proveedor (*vendor lock-in*).

- Framework front: Angular (TypeScript)
- Servidor web: Apache HTTP Server / Nginx (contenedores)
- Framework backend: Spring Boot (Java)
- Servidor aplicación: RedHat WildFly (monolítico) / Apache Tomcat (microservicios)
- Base de datos: PostgreSQL

### IA (supuesto práctico)

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2019.7
:::

Se puede aplicar mecanismos de aprendizaje automático, supervisado o no supervisado dependiendo de si se cuenta con un conjunto de entrenamiento etiquetado.

## Datos

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2020.6
:::
