## Dimensionamiento

Durante el diseño de un sistema informático se deben dimensionar cada uno de los elementos que forman parte del mismo.

Estos elementos se puede dividir en distintas tipologías de recursos que pueden dimensionarse por separado. Las tipologías a tener en cuenta son al menos:
| Licencia VMWare servidor | 5.000 |
- Desarrollo
- Licencias de software
- Infraestructura

Una vez dimensionadas cada tipología de recursos debe calcularse el coste asociado a cada una. Para ello, se debe revisar el apartado de [costes](#costes).

### Dimensionamiento de desarrollo

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- **🎯 Temas:**
  - 99. Estimación de recursos
- **🔗 Referencias de consulta:**
  - [Software Estimation](https://runmodule.com/2026/06/25/software-estimation/){target="_blank"}. RunModule, 2026.
:::

En caso de que el enunciado del ejercicio incluya un importe de presupuesto, el coste total del proyecto debe aproximarse lo más posible al indicado.

Los costes de un proyecto vienen definidos principalmente por:

- Esfuerzo de servicios de desarrollo
- Equipos informáticos de desarrollo
- Licencias de software de desarrollo

Las tarifas de personal no las he encontrado como estándares.

No obtante, las tarifas aparecen en algunas licitaciones públicas, como por ejemplo:

- en el Anexo IX de este otro contrato de la Comunidad de Madrid.
- Memoria económica del expediente 300/ 2021/00023 del Ayto de Madrid
- Servicio desarrollos evolutivos portales Madrid Destino del Ayto. de Madrid

Se realiza esta tabla buscando números redondos y ligeramente superiores a los de los expedientes citados.

#### Esfuerzo de servicios de desarrollo

En este apartado resume métodos de estimación de esfuerzo y costes en el desarrollo de software, que es una tarea habitual en el supuesto práctico.

De cara al supuesto práctico, se propone aplicar cada una de las técnicas de dimensionamiento de desarrollo en las siguientes situaciones:

- Si se cuenta con un diagrama de casos de uso: UCP.
- Si se cuenta con un modelo entidad-relación (ER) o un diagrama de clases: staffing size.
- En otro caso: COSMIC-FSM.

Algunas de estas técnicas se presentan en la documentación de estimación de recursos del temario de Astic (UCP y COSMIC-FSM), junto a otras no reseñadas en esta guía como el enfoque COCOMO o las métricas bang, mientras que otras provienen de Métrica v3 (staffing size). Adicionalmente, existen otras técnicas de estimación no cubiertas ni en la documentación de Astic ni en esta guía, y que nada impide que sean usadas en el ejercicio práctico.

##### User Case Points (UCP) {.unnumbered .unlisted}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- **🎯 Temas:**
  - 99. Estimación de recursos
- Referencias:
  - Murali Chemuturi. "[Software Estimation Best Practices, Tools & Techniques: A Complete Guide for Software Project Estimators](https://openlibrary.org/works/OL13780392W/Software_estimation_best_practices_tools_techniques?edition=key%3A/books/OL23218700M){target="_blank"}", J. Ross Publishing, 2009
  - Alan R. Dennis, Barbara Haley Wixom, and David Tegarden. Chapter 5 - Functional Modeling. In: [Systems Analysis and Design with UML Version 2.0: An Object-Oriented Approach](https://openlibrary.org/works/OL13780392W/Software_estimation_best_practices_tools_techniques?edition=key%3A/books/OL23218700M){target="_blank"}. 3rd ed. J. Ross Publishing, 2009.
  - Carl Friedrich Kress, Olivier Hummel, Mahmudul Huq, [A Practical Approach for Reliable Pre-Project Effort Estimation](https://ceur-ws.org/Vol-1138/re4p21.pdf){target="_blank"}.
  - [Use Case Points](https://en.wikipedia.org/wiki/Use_case_points){target="_blank"}
  - [Use Case Points](https://runmodule.com/2027/04/13/use-case-points/){target="_blank"}.
:::

Los puntos de caso de uso (use case points, UCP), a veces referidos como el método Karner, es un método de estimación de software basado en la complejidad de los casos de uso. Es por tanto adecuado cuando el supuesto práctico pide realizar un diagrama de caso de uso además de la estimación.

Fue desarrollado por Gustav Karner en 1993 mientras trabajaba en la compañía sueca Objectory Systems.

Hay un buen ejemplo en la [Wikipedia](https://en.wikipedia.org/wiki/Use_case_points#Example){target="_blank"}.

El total de puntos de casos de uso se calcula mediante la siguiente fórmula:
$$\text{UCP} = \text{UUCP} * \text{TCF} * \text{ECF}$$

Los puntos de casos de uso sin ajustar (*Unadjusted Use Case Points*, UUCP) se calculan como:

$$\text{UUCP} = \text{UUCW} + \text{UAW}$$

por lo que

$$\text{UCP} = (\text{UUCW} + \text{UAW}) * \text{TCF} * \text{ECF}.$$

El peso de caso de uso sin ajustar (Unadjusted Use Case Weight, UUCW) se calcula como:

| Use Case Classification | No. of Transactions | Weight | 
| - | - | - |
| Simple | 1-3 | 5 |
| Average | 4-7 | 10 |
| Complex | ≥8 | 15 |

$$UUCW = \sum{\text{no. de casos de usos} \times \text{peso}}$$

El peso de actor sin ajustar (Unadjusted Actor Weight, UAW) se calcula como:

| Actor Classification | Type of Actor Interaction | Weight |
| - | - | - |
| Simple | API | 1 |
| Average | Communication protocol | 2 |
| Complex | GUI | 3 |

$$UAW = \sum{\text{no. de actores} \times {peso}}$$

El factor de complejidad técnica (*technical complexity factor*, TCF) depende de la complejidad de la solución.

El factor de complejidad de ambiente (*environmental complexity factor*, ECF) depende de la experiencia del equipo de desarollo.

En un ejercicio completo se emplearían tablas y fórmulas para calcular el TCF y el ECF. De cara al ejercicio práctico, puesto que no se dispone de una copia de las tablas y fórmulas, calculadora y tiempo suficiente, para facilitar las cuentas se puede considerar que el TCF y el ECF son 0.8 y 1.25 (en el orden indicado, ya que son sus valores medios) para obtener un producto de 1 y facilitar las cuentas.

Una vez obtenidos los UCP, estos se transforman a horas. Puede ser tan sencillo como considerar un número de hroas fijos por caso de uso.

##### Staffing size {.unnumbered .unlisted}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias:
  - Ministerio de Administraciones Pública. Apartado "Staffing size (Orientación a objetos)". En: [Métrica v3. Técnicas](https://administracionelectronica.gob.es/pae_Home/dam/jcr:da7d91fa-d6bd-467c-be32-a72e27c603b3/METRICA_V3_Tecnicas.pdf){target="_blank"}. PAe.
  - Manuel Cillero. [Staffing size (Orientación a objetos)](https://manuel.cillero.es/doc/metodologia/metrica-3/tecnicas/staffing-size/){target="_blank"}. manuel.cillero.es
  - <https://runmodule.com/2027/04/27/cosmic-functional-size-measurement/>{target="_blank"}
- Temas:
  - 99. Estimación de recursos
:::

Staffing size es un método para estimar cuántas personas son necesarias en un desarrollo orientado a objetos y durante cuánto tiempo participan. Está incluido dentro de las técnicas de Métriva v3.

Es adecuado cuando el enunciado requiera hacer previamente un diagrama de clases o un modelo entidad-relación (E-R).

Se puede asumir que cada clase de producción lleva entre 10-15 días (100 horas), y las clases de prototipado 6-8 días.

##### Puntos de función {.unnumbered .unlisted}

Estimación por puntos de función (versión simplificada, problemente basada en COSMIC-FSM):

1. Identificar los puntos de función de enunciado
2. Estimar puntos de función
   Interfaz de usuario = 10 PF
   Módulo = 10, 20 ó 30 PF
3. Estimar horas
   Donde 1 PF = 10 horas

Una vez que se obtienen las horas de construcción (que se correspondería con la fase CSI de Métrica v3), se puede inferir que es el 40% o 50% del esfuerzo total.

El esfuerzo total en horas se obtendría multiplicando las horas de construcción por 2,5 (ya que 1/0,40 = 2,5), o incluso multiplicando por 2 (suponiendo un 50%, ya que 1/0,50 = 2).

##### COSMIC-FSM {.unnumbered .unlisted}

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias:
  - Miguel Ángel Rodrigo Muñoz. Apartado 2.3 "Ejemplo para medir el software o componente a desarrollar" y 2.5 "COSMIC-FSM". En: "Tema 98. La estimación de recursos y esfuerzo en el desarrollo de sistemas de la información". Astic, Sep-2022.
  - [COSMIC Method. Introduction](https://cosmic-sizing.org/cosmic-sizing/intro/){target="_blank"}.
  - [COSMIC functional size measurement](https://en.wikipedia.org/wiki/COSMIC_functional_size_measurement){target="_blank"}. Wikipedia.
  - <https://runmodule.com/2027/04/27/cosmic-functional-size-measurement/>{target="_blank"}
- Temas:
  - 99. Estimación de recursos
:::

COSMIC-FSM es una técnica de dimensionamiento funcional basada en el comportamiento del software y el movimiento de datos. La principal ventaja de COSMIC-FSM es que no requiere haber modelado previamente el caso.

El Consorcio Internacional de Medidas de Software Común (*Common Software Measurement International Consortium*, COSMIC) fue creada in 1998. Adaptó la idea de IFPUG FPA a las nuevas tendendicas de desarrollo, dando lugar a la técnica de COSMIC-FSM. Se ha estandarizado bajo el estándar ISO/IEC 19761, siendo la última versión [ISO/IEC 19761:2011](https://www.iso.org/standard/54849.html){target="_blank"}.

La técnica consiste en contar el total de puntos de función COSMIC (*COSMIC function points*, CFP) en un sistema, donde se cuenta 1 CFP por cada elemento de esta tipología encontremos:

- Entrada
- Salida
- Lectura
- Escritura

El método requiere que se cuenten con proyectos anteriores para los que sea conocido sus CFPs, coste y duración total, de manera que se pueda aplicar una regla de tres para calcular el tiempo o el coste dados los CFPs del nuevo proyecto.

$$ t_2 = \frac{\text{CFP}_2 \times t_1}{\text{CFP}_1} $$

$$ c_2 = \frac{\text{CFP}_2 \times c_1}{\text{CFP}_1} $$

Puesto que es poco probable de que en el supuesto práctico del CSSTIE contemos con información sobre rendimiento por CFP en base a proyecto anteriores, si queremos emplear esta técnica debemos suponer un coste y duración por CFP estimados. Por ejemplo, 1 CFP puede corresponder con 10 horas de trabajo (aunque en el ejemplo de la bibliografía de Astic 1 PF = 100).

Por otro lado, el coste se puede obtener directamente conviertiendo los CFPs en horas empleando un coeficiente supuesto (ej. 1 CPF = 1.000 €), o si no de forma más compleja, pues que ya se tiene el número de horas de trabajo por la suposición anterior, aplicar las tarifas de los empleados.

#### Servicios de desarrollo

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Contratación
  - SDA 25/2022 de suministros
- Referencias
  - [Métrica v3](https://administracionelectronica.gob.es/pae_Home/pae_Documentacion/pae_Metodolog/pae_Metrica_v3.html?idioma=es){target="_blank"}. PAe.
  - [Métrica v3. Participantes](https://administracionelectronica.gob.es/pae_Home/dam/jcr:d601853c-e255-4ade-a9f8-af1357e3a151/METRICA_V3_Participantes.pdf){target="_blank"}. PAe, 2001.
  - Manuel Cillero, [Métrica v3. Participantes](https://manuel.cillero.es/doc/metodologia/metrica-3/participantes/){target="_blank"}, manuel.cillero.es.
:::

Es importante dejar claro en el ejercicio práctico y durante las preguntas de la lectura de que para el sistema se contratan servicios de desarrollo, no de personal.

La metodología Métrica v3, en su documento de [Participantes](https://administracionelectronica.gob.es/pae_Home/dam/jcr:d601853c-e255-4ade-a9f8-af1357e3a151/METRICA_V3_Participantes.pdf){target="_blank"}, define una serie de perfiles de participantes en el desarrollo de sistemas de información:

- Directivo
- Jefe de Proyecto
- Consultor
- Analista
- Programador

Adicionalmente, en algunos pliegos contemporáneos (como [este](https://contrataciondelestado.es/FileSystem/servlet/GetDocumentByIdServlet?DocumentIdParam=tNPjeO7M69nK%2BJEppP2WhnzXW3zzgJBktRjJpSJDeGVqean%2FKThYS%2Bkgg1JnKHv8t0vVPmZvaP7Bqss5p37%2FNFsxObzsp3%2FUnFfyMeR6S1h45ClyWkoJ44mKM70IFcOu&cifrado=QUC1GjXXSiLkydRHJBmbpw%3D%3D){target="_blank"}) se menciona adicionalmente el perfil de analista-programador. Este perfil mixto no figura en Métrica v3 pero sí se aparece en el [XII Convenio Colectivo Estatal de Empresas de Consultoría y Planificación](https://www.boe.es/buscar/doc.php?id=BOE-A-2000-17579){target="_blank"} de 2000, lo cual puede ser una posible explicación sobre su uso.

Con respecto a categoría y tarifa, esta guía considera análogos los perfiles de analista y analista-programador, justificándose en que en Métrica v3 no existe el perfil mixto.

A efectos prácticos, para  puede establecer que un desarrollo necesita el siguiente número de perfiles:

- 1 jefe de proyecto por proyecto
- Tantos analistas-programadores como sea necesario para tener el proyecto en la fecha indicada en el enunciado o en un periodo razonable (6-18 meses).
- Analistas en un ratio de 0,25-0,5 respecto al número total de programadores.
- Opcionalmente 1 o 2 consultores, en función del presupuesto disponible.

Se suele reducir el ratio de analistas por programador cuando interesa reducir el coste de desarrollo.

También se puede convertir a un analista en analista-programador cuando interese aumentar el número perfiles de programadores sin reducir el ratio de analistas por cada programador.

Este criterio está basada en la definición de Unidad de Trabajo de la licitación de los [Servicios de Desarrollo y Mantenimiento del Registro Único de Protonterapia (RUP) para el Sistema Nacional de Salud](https://contrataciondelestado.es/FileSystem/servlet/GetDocumentByIdServlet?DocumentIdParam=tNPjeO7M69nK%2BJEppP2WhnzXW3zzgJBktRjJpSJDeGVqean%2FKThYS%2Bkgg1JnKHv8t0vVPmZvaP7Bqss5p37%2FNFsxObzsp3%2FUnFfyMeR6S1h45ClyWkoJ44mKM70IFcOu&cifrado=QUC1GjXXSiLkydRHJBmbpw%3D%3D){target="_blank"}, donde se definía que una unidad de trabajo estaba formada por:

- 1 jefe de proyecto
- 3 analistas
- 6 analistas-programadores

Otro criterio es suponer que un proyecto típico tiene 12 personas: 1 jefe de proyecto, 2 analistas y 8 programadores. Adicionalmente se puede poner 1 consultor, jugando con esto en función del presupuesto disponible.

#### Equipos informáticos de desarrollo

Cada uno de los perfiles necesarios para el proyecto requiere un equipo informático.

#### Licencias de software para desarrollo

Las estaciones de trabajo (*workstations*) de la AGE suelen usar el SO Microsoft Windows. Puesto que los equipos de desarrollo se adquieren con licencias OEM (*original equipment manufacturer*) del sistema operativo, no es necesario dimensionar por separado estas licencias.

Se puede justificar el no incluir licencias de herramientas de desarrollo argumentando que se emplean herramientas de software libre y de código abierto.

### Dimensionamiento de infraestructuras

Para realizar el dimensionamiento de infraestructuras se requiere haber diseñado previamente un 

Si el sistema cuenta con infraestructura *on premise*, se puede emplear el [SDA 24/2022](#sda242022) de sistemas de comunicación, servidores y sistemas de almacenamiento.

Si el sistema depende de infraestructura en la nube, se demostrará al Tribunal conocimiento sobre la AGE al proponer el uso de la [NubeSARA](#nubesara). Conviene revisar y aplicar las tarifas correspondientes.

#### Servidores

Se debe contar el número de servidores

También se deben dimensionar las licencias de software de los servidores.
