## Contratación

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Regulaciones
  - UE
    - Directiva 2014/24/UE
    - Directiva 2014/23/UE
    - Directiva 2014/25/UE
  - España
    - RD 1098/2001
    - RDL 3/2011
    - [L 9/2017. CSP 2 / LCSP](02-analisis#BOE-A-2017-12902)
    - RDL 3/2020
    - RD 806/2014. Organización e intrumentos operativos de TIC en ADE
- Temas
    - 11. Los contratos de las Administraciones Públicas
- Referencias
  - <https://runmodule.com/2026/01/27/contratacion-en-el-sector-publico-de-espana/>
:::

Este apartado trata sobre la contratación en la Administración General del Estado (AGE).


Contratación

Puedes leer más en este artículo sobre contratación en el sector público.

Ciñéndonos en los tipos de contratación de servicios y suministros, que son los más comunes en el supuesto práctico, con su restricción en el valor estimado:

Tipo de contratoLímite importeTiempoEncargos a medios propiosContrato menor<15.000 €1 mesContratación centralizada< 862.000 €2 mesesProcedimiento abierto simplificado abreviado< 60.000 €Procedimiento abierto simplificado< 143.000 €Procedimiento abiertoSin límites6 meses

Los tiempos están tomados de los apuntes de Andreu Bosa.

Cuando más simplificado y rápido sea el proceso mejor. Esto influirá en el cronograma del proyecto.

Los trámites de urgencia permiten reducir a la mitad los tiempos, si bien no se pueden reducir tiempos de los periodos de alegaciones.

Es conveniente comprobar si debido al importe están sujetos a regulación armonizada (SARA). El límite para la AGE en servicios y suministros es 143.000 €.



<!-- Cuando el importe del contrato supere los 12.000.000 € debe aprobarse también por el Consejo de Ministros.

### Presupuesto de los contratos

- Presupuesto base de licitación
- Valor estimado
- Precio

#### Presupuesto base de licitación

El presupuesto base de licitación es el límite máximo de gasto que en virtud del contrato puede comprometer el órgano de contratación, incluido el Impuesto sobre el Valor Añadido (IVA).

No incluye prórrogas.

Incluye IVA.

#### Valor estimado

El valor estimado incluye todas las prórrogas y modificaciones.

NO incluye IVA.

### Tipos de contratación pública según su objeto

Tipos de contratación según su objeto:

- Obras
- Concesión de obras
- Servicios
- Concesión de Servicios
- Suministros
- Mixto

Las licencias de software se considera suministro, mientras que el software a medida se considera un servicio.

#### Obras

El contrato de obras se regula en el art. 13 de la ley 9/2017.

#### Mixto

En el contrato mixto se recogen varios objetos de contratación. 

En caso de contrato mixto, se distingue entre la preparación y adjudicación del contrato, donde se recogen las normas que establecen las Directivas, y los efectos y extinción.

Respecto de la preparación y adjudicación, la regla general es que al contrato mixto se le aplican las normas del contrato cuya prestación sea la principal o cuyo valor estimado sea más elevado.

### Regulación armonizada SARA

La regulación armonizada (SARA) es una regulación que se aplica solamente a contratos que cumplen ciertas características.

La regulación armonizada sre aplica cuando el valor estimado del contrato sobrepasa el umbral de:

143.000 € para la AGE en contratos de suministros y servicios

221.000 € para organismos distintos a la AGE en contratos de suministros y servicios

5.538.000 € en contratos de obras, concesión de obras y de concesión de servicio (para cualquier organismo

Estos importes se establecen en la Orden HFP/1352/2023.

Una de las implicaciones de la regulación armonizada es que los contratos bajo la misma deben publicarse en el Diario Oficial de la Unión Europea.

### Plazo de ejecución

El plazo de ejecución se especifica en el pliego, sin que exista un plazo máximo. Los plazos de ejecución se regulan en el art. 210 de la ley 9/2017.

### Prórrogas en concesiones

Las prórrogas de las concesiones deben ser acordadas entre la entidad contratante y el contratista.

Vienen reguladas en el art. 205 de la ley 9/2017.

### Procedimientos de adjudicación

Procedimientos o formas de adjudicación:

- Procedimiento abierto
- Procedimiento abierto simplificado
- Procedimiento abierto simplificado abreviado
- Procedimiento restringido
- Procedimiento de negociación
- Procedimiento negociado sin publicidad
- Contrato menor
- Diálogo competitivo
- Procedimiento de asociación para la innovación
- Contrato menor
- Contratación centralizada

La plataforma para realizar contratación es Conecta-Contratación.

[Página web de Conecta-Contratación](https://catalogocentralizado.hacienda.gob.es/pctw/Acceso/inicio.aspx).

Los contratos sujetos a contratación armonizada se llaman también contratos SARA.

#### Procedimiento abierto

Un procedimientos abierto se denomina así ya que cualquiera puede licitar al mismo.

Existen varios subtipos de procedimiento abierto:

- Procedimiento abierto (estándar)
- Procedimiento abierto simplificado
- Procedimiento abierto simplificado abreviado

**Procedimiento abierto estándar**

El procedimiento abierto es el ordinario de contratación. Se le llama en este apartado procedimiento abierto estándar para distinguirlo de variantes como el simplificado y el abreviado, aunque este no sea su nombre oficial.

El plazo de presentación de proposiciones es:

En caso de regulación NO armonizada: 15 días

En caso de regulación armonizada

En situación estándar: 35 días

Si se publicó un anuncio previo o en situación de emergencia: 15 días

Si se aceptan propuestas de ofertas por medios electrónicos, reducen los plazos en 5 días. Esto se define en el art. 156.3.c.

No tiene restricciones respecto al importe del contrato.

**Procedimiento abierto simplificado**

Condiciones para su aplicación:

Criterio económico

Para contratos de obras, valor estimado <= 2.000.000 €

Para contratos de suministro y de servicios, valor estimado <= 100.000 €

Criterios de adjudicación

En prestación de carácter no intelectual, los juicios de valor deben ser <25%

En prestación intelectual, los juicios de valor deben ser <40%

Plazo de presentación de proposiciones mínimo:

Obras: 20 días

Otros: 15 días

**Procedimiento abierto simplificado abreviado**

Condiciones para su aplicación:

Criterio económico

Para contratos de obras, valor estimado <= 80.000 €.

Para contratos de suministros y servicios, valor estimado <= 60.000 €

Tipo de prestación

Solo prestación de carácter no intelectual

Plazo de presentación de proposiciones mínimo:

Compras corrientes disponibles en el mercado: 5 días hábiles

Otros: 10 días hábiles

No es necesaria la acreditación de la solvencia económica y financiera y técnica o profesional de los licitadores.

La oferta se entregará en un único sobre y se evaluará con arreglo a criterios de adjudicación cuantificables mediante la mera aplicación de fórmulas establecidas en los pliegos.

Con "sobre único" se refiere a que solo se hace una oferta con valores cuantificables y que, a diferencia de otros procesos, no hace falta emitir aparte la oferta con valores subjetivos o cualitativos.

#### Procedimiento restringido

Solo puede licitar quien pasa un filtro.

No permite negociaciones en el precio.

#### Procedimiento con negociación

Estos procedimientos permiten negociación, a diferencia del abierto y el restringido.

Existen dos tipos:

- Procedimiento con negociación [estándar]
- Procedimiento con negociación sin publicidad

**Procedimiento con negociación estándar**

Viene recogido en el artículo 167 de la LCSP.

Permite negociar con los licitadores las condiciones, quedando fuera los aspectos esenciales y los criterios de adjudicación.

La versión estándar requiere publicidad.

Solo se puede aplicar en un número de casos:

Cuando requiera que los licitadores realicen un trabajo previo de diseño o adaptación.

Cuando se trate de una solución innovadoras

Cuando las negociaciones sean ineludibles.

Cuando el órgano de contratación con puede precisar suficientemente las especificaciones.

Cuando no se haya recibido nada aceptable tras realizar un procedimiento abierto o restringido.

Cuando se trate de contratos de servicios sociales personalísimos.

**Procedimiento negociado sin publicidad**

Regulado en el artículo 168 LCSP.

Es similar al procedimiento negociado estándar pero no requiere publicidad.

Requiere que se de una compleja lista de condiciones, entre ellas:

No se haya presentado ninguna oferta; ninguna oferta adecuada; ninguna solicitud de participación; o ninguna solicitud de participación adecuada en respuesta a un procedimiento abierto o a un procedimiento restringido.

Cuando las obras, los suministros o los servicios solo puedan ser encomendados a un empresario determinado.

Cuando el contrato haya sido declarado

#### Diálogo competitivo

Comparte los supuestos del procedimiento negociado.

Supone mantener una mesa de diálogo.

Permite el pago de primas o compensaciones a los licitadores que se presenten.

#### Procedimiento de asociación para la innovación

Relacionado con la innovación.

#### Contrato menor

Un contrato menor debe cumplir una serie de condiciones.

Condiciones del contrato menor:

- Condiciones económicas
  - Contratos de obras: valor estimado < 40.000.
  - Contratos de suministros o servicios: valor estimado < 15.000 €.

En este caso se define también en valor estimado y no al importe base de licitación.

Se debe solicitar al menos 3 prespuestos.

No se requerirá la aprobación del gasto, pero sí la incorporación al expediente de la factura correspondiente.

Los contratos menores NO son susceptbiles de prórroga.

Según los apuntes de Andreu Bosa, lleva un mes su tramitación.

#### Contratación centralizada

Modalidades dentro de la contratación centralizada:

- Acuerdo marco
- Sistema dinámico de adquisición (SDA)
- Contratos centralizados
- Encargos a medios propios

Por encima de 862.000 € no se puede ir por contratación centralizada y habría que ir muy probablemente a procedimiento abierto.

Se pueden revisar el catálogo en la página oficial:

[Página web del catálogo de contratación centralizada](https://contratacioncentralizada.gob.es/catalogo)

La tendencia es convertir los acuerdos marcos en sistemas dinámicos de adquisición (SDA), ya que son más flexibles y fomenta la competitividad y ofrece mayor transparencia.

La Secretaría General de la Administración Digital (SGAD) agrega todas las peticiones y la DGRCC coordina el proceso de compra conjunto.

#### Acuerdos Marco

La duración máxima de un acuerdo marco es de 2 años prorrogables a otros 2. Durante el plazo de vigencia del acuerdo marco no pueden entrar más proveedores.

En caso de que no estén todos los términos o condiciones fijados hay que añadir una segunda fase en la que hay que contactar a los proveedores.

En caso de contratos SARA hay que contactar a todos los proveedores del acuerdo marco.

En caso de contratos no SARA es suficiente con contactar con 3 proveedores.

El órgano de contratación es, como norma general, la Dirección General de Racionalización y Centralización de la Contratación (DGRCC).

Acuerdos marcos relevantes para IT:

- AM 02/2023. Ordenadores de mesa, portátiles monitores y otras soluciones del puesto de trabajo
- AM 05/2023. Impresoras, fotocopiadoras y escáneres
- AM 08/2021. Sistemas de seguridad

Hay que saberse los números de los acuerdos marcos.

**AM 02/2023 {am022023}**

<https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-ami-suministro-ordenadores>

#### Sistemas Dinámicos de Adquisición

Sistemas dinámicos de adquisición (SDA) tiene una duración de 5 años.

Durante su vigencia se permiten que salgan y entren empresas.

SDAs relevantes para TI:

- [SDA 25/2022](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-sda-suministro-de-software). Suministro de software
- [SDA 26/2021](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-sda-servicios-de-desarrollo). Servicios de desarrollo
- [SDA 24/2022](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-sda-suministro-servidores). Suministro de equipos de comunicaciones, servidores y sistemas de almacenamiento

**SDA 25/2022. Suministro de software {#sda252022}**

**SDA 26/2021. Servicios de desarrollo {#sda262021}**

SDA 26/2021, de servicios de desarrollo, permite contratos de hasta un máximo de 862.000 € excluidos impuestos, prórrogas y modificaciones contractuales.

**SDA 24/2022. Suministro de equipos de comunicaciones, servidores y sistemas de almacenamiento {#sda242022}**

#### Contratos centralizados

Los contratos centralizados son aquellos que se sirven a todas las administraciones públicas en un único contrato.

En el caso de telecomunicaciones existen 4 lotes:

- Lote 1. Fijo. Adjudicado a Telefónica
- Lote 2: Móviles. Otorgado a Vodafone
- Lote 3: Internet. Otorgado a Telefónica.
- Lote 4: Internacional. Adjudicado a British Telecom (BT)

### Modificación de Contratos

Los pliegos de cláusulas administrativas particulares deben advertir expresamente la posibilidad de modificación y el importe de esta no podrá superar el veinte por ciento del precio inicial del contrato.

#### Encargos a medios propios

Los encargos a medios propios son mecanismos para que se hagan encargos a organismos relacionados con la AGE.

Las encomiendas de gestión no hay una relación vinculante entre encomentante y encomendado.

Son disitntos los encargos a medios propios y las encomiendas de gestión.

La definición de medio propio incluye:

No tener inversión privada.

No tener más de un 20% de actividad en sector privado.

Un ejemplo de medio propio sería la Fábrica Naciona de Moneda y Timbre-Real Casa de la Moneda (FNMT-RCM).

### Anuncios de licitaciones público

Los procedimientos negociados sin publicidad no se publican.

El resto de licitaciones se anuncian en la Plataforma de Contratación del Sector Público.

Las licitación de organismos de la AGE se publican además en el Boletín Oficial del Estado.

Las licitaciones sujetas a regulación armonizada (SARA) se publica en el Diario Oficial de la Unión Europea.

### Procedimiento general de contratación TIC

Pasos técnicos:

1. Análisis de necesidades
2. Especificaciones ténico-funcionales
3. Evaluación y selección de ofertas
4. Validación y pruebas

Actividades del análisis de contratación:

1. Planificación de la capacidad del S.I.
2. Decisiones HW / SW
3. Decisiones sobre la rentabilidad económica

Estos tres puntos se desarrollan en los temas 2023.40, 2024.41 y 2024.42 de TIC, que no sueen entrar mucho.

Expediente de contratación:

- Memoria
- Certificado
- Pliegos
  - Pliego de Cláusulas Administrativas Particulares (PCAP).
  - Pliego de Prescripciones Técnicas (PPT).
- Informes preceptivos de la Memoria y de los Pliegos
  - Para el PCAP, lo realiza el servicio jurítico de la abogacía del estado
  - La memoria y el PPT lo realiza el SGAD
- Informe de fiscalización por la Intervención Delegada

El Pliego de Cláusulas Administrativas general (PCAG) consta de unas diapositivas.

El PCAP tiene carácter legal y contractual.

En la administración pública nunca se contratan personas. Se contratan solamente servicios y se necesitan personas para cubrir esos servicios.

En caso de retraso en al ejecución del contrato en proporción de 0,60 € por cada 1.000 €. En caso de que se supere el 5% del total se puede rescindir el contrato.

Hay un proceso de recepción de la inversión. En ella está involucrado un técnico gestor.

Corenet es una aplicación de la Intervención General de la Administración del Estado (IGAE) para revisar la recepción de contrato de más de 50.000 € a través de un interventaror de la IGAE. Suele ser un perfil TIC dentro de este organismo. -->
