## Planificación temporal

Este apartado trata sobre la planificación de desarrollo de software, que es una tarea habitual en el supuesto práctico del ejercicio práctico del CSSTIAE.

En la planificación temporal hay que tener en cuenta los siguientes factores:

- Tiempo mínimo de contratación
- Esfuerzo de desarrollo

### Aspectos generales de planificación

El input recibido en la planificación sería:

- Horas totales por desarrollador

En la planificación hay que tener en cuenta:

- Número de horas totales
- Número de programadores
- Tiempo de contratación

El número de horas totales hay que dividirlas entre el número de programadores.

En caso de que hayamos calculado el esfuerzo en días (por ejemplo, al usar staffing size):

- 1 mes = 20 días laborables
- 6 meses = 120 días laborables
- 1 año = 240 días laborales.

En caso de que hayamos calculado el esfuerzo en horas:

- 1 mes ~ 150 horas
- 3 meses ~ 500 horas
- 6 meses = 960 horas ~ 1.000 horas
- 1 año = 1.920 horas ~ 2.000 horas

### Fases de un proyecto

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Referencias
  - Manuel Cillero, [Métrica v3](https://manuel.cillero.es/doc/metodologia/metrica-3/), manuel.cillero.es.
:::

Las fases de un proyecto de sistemas informáticos de la AGE se pueden definir en base al Desarrollo de Sistemas de Información de Métrica v3:

1. Estudio de viabilidad del sistema (EVS)
2. Análisis del sistema de información (ASI)
3. Diseño del sistema de información (DSI)
4. Construcción del sistema de información (CSI)
5. Implantación y aceptación del sistema (IAS)
6. Mantenimiento del sistema de información (MSI)

### Metodologías

- Referencias:
  - Elisa Martín Ortega. Tema 86. *El ciclo de vida de los sistemas de información. Modelos del ciclo de vida.*. Astic, 2023.
  - Vanesa Mancebo Domínguez. Tema 87. *Análisis funcional de sistemas, casos de uso e historias de usuario. Metodologías de desarrollo de sistemas. Metodologías ágiles: Scrum y Kanban*. Astic, 2017.
- Temas:
  - 86. Modelos de ciclo de vida.
  - 88. Análisis de sistemas y metodologías ágiles.

Se debe escoger una metodología del sistema.

En caso de escoger alguna metodología ágil basada en SCRUM, se deben reflejar los sprints.
