## Contratación

::: {.callout-note collapse="true" icon="false"}
## 📝 Apariciones en examen
Convocatorias/tareas: 2020.8, 2019.5
:::

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Regulaciones
  - UE
    - [Directiva 2014/24/UE](02-analisis.qmd#celex:32014L0024)
    - Directiva 2014/23/UE
    - Directiva 2014/25/UE
  - España
    - RD 1098/2001
    - RDL 3/2011
    - **[L 9/2017. Contratación del Sector Público (CSP 2 / LCSP)](02-analisis#BOE-A-2017-12902)**
    - RDL 3/2020
    - RD 806/2014. Organización e intrumentos operativos de TIC en ADE
- Temas
    - 11. Los contratos de las Administraciones Públicas
- Referencias
  - <https://runmodule.com/2026/01/27/contratacion-en-el-sector-publico-de-espana/>
:::

En este apartado se cubren aspectos relacionados con la contratación en la Administración General del Estado (AGE).

Lo más importante de este tema de cara al supuesto práctico es ser capaz de:

- Identificar si un contrato es SARA, y en caso afirmativo, comprender sus implicaciones
- Distinguir los distintos procedimientos de contrataciones con sus umbrales y conocer los tiempos de espera que requieren
- Identificar los acuerdos marcos (AM) más relevantes para IT, saber cuándo aplicarlos
- Identificar los sistemas dinámicos de adquisición (SDA) más relevantes para IT, y saber cuándo aplicarlos

Conocer los tiempos que implica la contratación es un requisito necesario para realizar la planificación temporal, que es solicitada a menudo en el supuesto práctico.

### Proceso de contratación en supuesto práctico

En este apartado se resume el proceso de contratación pública, tal y como se plantea en el supuesto práctico. Como requisito para poder comenzar la contratación, se deben haber identificado todos sus costes junto con su naturaleza.

Pasos del proceso de contratación en el supuesto práctico:

1. **Tipología**: Asignar cada uno de los gastos a una tipología de contratación según objeto (ej.: suministros, servicios)
2. **Urgencia**: Comprobar si aplica la tramitación urgente
3. **Centralización**: Incluir todos los gastos posibles en contratación centralizada (ej.: AM, SDA).
4. **Descentralización**: Evaluar el procedimiento de contratación aplicable a los gastos restantes
5. **SARA**: Comprobar si el contrato está sujeto a regulación armonizada (SARA), y en caso afirmativo, explicar implicaciones.
6. **Consejo de Ministros**: Comprobar si el contrato debe ser aprobado por Consejo de Ministros (>12M€).
7. **Lotes**: Dividir en lotes

Resumen de tipologías de contratación pública, con sus límites y tiempos:

| Tipología | Límite importe (serv. y sum.) | Tiempo para comenzar |
| - | - | - |
| Encargos a medios propios | sin límite | Inmediato |
| Contrato menor | < 15.000 € | 1 mes |
| Contratación centralizada | < 862.000 € | 2 meses |
| Procedimiento abierto simplificado abreviado | < 60.000 €  | 2 meses |
| Procedimiento abierto simplificado | < 140.000 € | 4 meses |
| Procedimiento abierto | Sin límite | 6 meses |

En este resumen los límites están simplificados y focalizados en servicios de desarrollos (como el SDA 26/2021) en los casos en los que haya varias casuísticas.

Contratación centralizada más relevante:

| Código | Descripción |
| - | - |
| [AM 02/2023](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-ami-suministro-ordenadores) | Ordenadores de mesa, portátiles monitores y otras soluciones del puesto de trabajo |
| [AM 05/2023](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-ami-impresoras) | Impresoras, fotocopiadoras y escáneres |
| [AM 08/2021](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-ami-sistemas-seguridad) | Sistemas de seguridad |
| [SDA 25/2022](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-sda-suministro-de-software) | Suministro de software |
| [SDA 26/2021](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-sda-servicios-de-desarrollo) | Servicios de desarrollo |
| [SDA 24/2022](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-sda-suministro-servidores) | Suministro de equipos de comunicaciones, servidores y sistemas de almacenamiento |

Evaluación del proceso de contratación:

- Escoger el proceso de contratación más simplificado y rápido disponible.
- Si se aplica trámite de urgencia permiten reducir a la mitad los tiempos, si bien no se pueden reducir tiempos de los periodos de alegaciones.

### Conceptos generales de contratación pública

#### Marco normativo de contratación pública

La Directiva 2014/24 es la más general de las de la UE relativas a la contratación del sector público. Esta se traspuso en la [ley 9/2017](02-analisis#BOE-A-2017-12902), también conocida como CSP2 o LCSP, que es la norma principal en el estudio de este apartado.

El resumen de los tipos de contratación de servicios y suministros, los más comunes en el supuesto práctico, junto con su restricción en el valor estimado, son los siguientes:

#### Conceptos relacionados con contratos

- Expedientes
- Lotes
- Presupuesto base de licitación
- Valor estimado
- Precio

##### Expedientes {.unnumbered .unlisted}

Los expedientes representan una serie de necesidades relacionadas con un mismo proyecto.

##### Lotes {.unnumbered .unlisted}

Los expedientes se dividen en lotes. Cada lote tiene su propia licitación.

##### Presupuesto base de licitación {.unnumbered .unlisted}

El presupuesto base de licitación es el límite máximo de gasto que en virtud del contrato puede comprometer el órgano de contratación, incluido el Impuesto sobre el Valor Añadido (IVA).

No incluye prórrogas.

Incluye IVA.

##### Valor estimado {.unnumbered .unlisted}

El valor estimado incluye todas las prórrogas y modificaciones.

NO incluye IVA.

#### Proceso interno de contratación

El proceso de contratación pública requiere una serie de tareas internas en la AAPP, que de cara al supuesto práctico generalmente se obvian aunque siguen siendo cuestionables, como por ejemplo:

- Revisión de jurídico.
- Realización del presupuesto.
- Fiscalización de Intervención.
- Convocatoria de Mesa de Contratación se convoca con carácter prioritario.
- Realización de informes de valoración técnica.
- Firmas.

### (Paso 1) Tipología de contratación pública según su objeto

La LCSP considera las siguientes tipologías de contratación pública según su objeto:

- Obras
- Concesión de obras
- Servicios
- Concesión de servicios
- Suministros
- Mixto

| Objeto | Art. LCSP |
| - | - |
| Obras | 13 |
| Concesión de obras |  14 |
| Servicios | 15 |
| Concesión de servicios | 17  |
| Suministros | 16  |
| Mixto | 18 |

Las licencias de software se considera suministro, mientras que el desarrollo de software se considera un servicio. En el supuesto práctico lo habitual es que se consideren solo estas dos tipologías junto con mixto.

#### Mixto

En el contrato mixto se recogen varias tipologías distintas en un mismo objetos de contratación. 

En caso de contrato mixto, se distingue entre la preparación y adjudicación del contrato, donde se recogen las normas que establecen las Directivas, y los efectos y extinción.

Respecto de la preparación y adjudicación, la regla general es que al contrato mixto se le aplican las normas de la tipología cuya prestación sea la principal o cuyo valor estimado sea más elevado.

### (Paso 2) Tramitación de urgencia

La tramitación de urgencia se regula en el art. 119 de la LCSP.

Se puede declarar la urgencia en un expediente de contratación cuando se cumpla alguna de estas condiciones:

- La Administración tiene que actuar de manera inaplazable.
- Es necesario acelerar la adjudicación por razones de interés público.

Como normal general, los tiempos se reducen a la mitad.

Como nota, hay subprocesos dentro de la contratación qeu no pueden ser reducidos, como las alegaciones no el plazo de presentación de ofertas de los procesos simplificados. No obstante, el proceso de contratación completo sigue reduciéndose a la mitad.

### (Paso 3) Contratación centralizada

Modalidades dentro de la contratación centralizada:

- Acuerdo marco (AM)
- Sistema dinámico de adquisición (SDA)
- Contratos centralizados
- Encargos a medios propios

Por encima de 862.000 € no se puede ir por contratación centralizada y habría que ir muy probablemente a procedimiento abierto.

Se pueden revisar el catálogo en la página oficial:

[Página web del catálogo de contratación centralizada](https://contratacioncentralizada.gob.es/catalogo)

La tendencia es convertir los acuerdos marcos en sistemas dinámicos de adquisición (SDA), ya que son más flexibles y fomenta la competitividad y ofrece mayor transparencia.

La Secretaría General de la Administración Digital (SGAD) agrega todas las peticiones y la DGRCC coordina el proceso de compra conjunto.

#### Acuerdos Marco

La duración máxima de un acuerdo marco es de 2 años prorrogables a otros 2. Durante el plazo de vigencia del acuerdo marco no pueden entrar más proveedores.

En caso de que no estén todos los términos o condiciones fijados hay que añadir una segunda fase en la que hay que contactar a los proveedores.

En caso de contratos SARA hay que contactar a todos los proveedores del acuerdo marco.

En caso de contratos no SARA es suficiente con contactar con 3 proveedores.

El órgano de contratación es, como norma general, la Dirección General de Racionalización y Centralización de la Contratación (DGRCC).

Acuerdos marcos relevantes para IT:

- [AM 02/2023](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-ami-suministro-ordenadores). Ordenadores de mesa, portátiles monitores y otras soluciones del puesto de trabajo
- [AM 05/2023](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-ami-impresoras). Impresoras, fotocopiadoras y escáneres
- [AM 08/2021](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-ami-sistemas-seguridad). Sistemas de seguridad

#### Sistemas Dinámicos de Adquisición

Cada Sistemas dinámicos de adquisición (SDA) tiene una duración de 5 años, y cada uno de ellos puede aplicar restricciones particulares que no apliquen al resto de SDAs..

Durante su vigencia se permiten que salgan y entren empresas, representando a un "club de proveedores" que tienen acceso a las licitaciones rápidas.

SDAs relevantes para TI:

- [SDA 25/2022](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-sda-suministro-de-software). Suministro de software
- [SDA 26/2021](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-sda-servicios-de-desarrollo). Servicios de desarrollo
- [SDA 24/2022](https://contratacioncentralizada.gob.es/web/dgrcc/-/ficha-sda-suministro-servidores). Suministro de equipos de comunicaciones, servidores y sistemas de almacenamiento

##### SDA 25/2022. Suministro de software {#sda252022}

Lote 1: Sw de sistema para la ejecución y desarrollo de aplicaciones
Lote 2: Sw para la gestión de infraestructura
Lote 3: Sw para la analítica de datos
Lote 4: Sw de ciberseguridad
Lote 5: Sw de aplicación para la administración digital
Lote 6: Sw de productividad y colaboración

##### SDA 26/2021. Servicios de desarrollo {#sda262021}

SDA 26/2021, de servicios de desarrollo, permite contratos de hasta un máximo de 862.000 € excluidos impuestos, prórrogas y modificaciones contractuales. Esta cláusula fue introducida por la Dirección Ge

##### SDA 24/2022. Suministro de equipos de comunicaciones, servidores y sistemas de almacenamiento {#sda242022}

Lote 1: Equipos de comunicaciones
Lote 2: Servidores y sistemas de almacenamiento 

#### Contratos centralizados

Los contratos centralizados son aquellos que se sirven a todas las administraciones públicas en un único contrato.

En el caso de telecomunicaciones existen 4 lotes:

- Lote 1. Fijo. Adjudicado a Telefónica
- Lote 2: Móviles. Otorgado a Vodafone
- Lote 3: Internet. Otorgado a Telefónica.
- Lote 4: Internacional. Adjudicado a British Telecom (BT)

### Modificación de Contratos

Los pliegos de cláusulas administrativas particulares deben advertir expresamente la posibilidad de modificación y el importe de esta no podrá superar el veinte por ciento del precio inicial del contrato.

#### Encargos a medios propios

Los encargos a medios propios son mecanismos para que se hagan encargos a organismos relacionados con la AGE.

Las encomiendas de gestión no hay una relación vinculante entre encomentante y encomendado.

Son disitntos los encargos a medios propios y las encomiendas de gestión.

La definición de medio propio incluye:

- No tener inversión privada.
- No tener más de un 20% de actividad en sector privado.

Un ejemplo de medio propio sería la Fábrica Naciona de Moneda y Timbre-Real Casa de la Moneda (FNMT-RCM).

### (Paso 5) Regulación armonizada SARA

La **regulación armonizada** o **SARA** es aquella se aplica a contratos del sector público de la UE que cumplen ciertas condiciones. Estas están especificadas en la Sección 2.ª "Contratos sujetos a una regulación armonizada" (a partir del artículo 19) la LCSP. Esta parte suele ser actualizada regularmente mediante órdenes. En 2026, la última orden aplicada fue la Orden HAC/1517/2025.

Un **contrato de regulación armonizada** o **contrato SARA** es aquel sobre el que se aplica la regulación armonizada.

#### Condiciones SARA {.unnumbered .unlisted}

Desde 2026, SARA se aplica cuando el valor estimado del contrato sobrepasa el **
umbral** de:

- 140.000 € para la AGE en contratos de suministros y servicios
- 216.000 € para organismos distintos a la AGE en contratos de suministros y servicios
- 750.000 € para contratos de servicios sociales y especiales especificados en el Anexo IV de la LCSP 
- 5.404.000 € en contratos de obras, concesión de obras y de concesión de servicio (para cualquier organismo)

Existen una serie de excepciones en los que no se aplica SARA especificadas en los art. 19.2. De manera muy sintetizada, serían los contratos relacionados con los servicios siguientes:

- Comunicación audiovisual
- Defensa
- Secretos o reservados
- Comunicaciones
- Servicios jurídicos
- Defensa civil, protección civil o gestión de riesgos
- Transporte público
- Abastecimiento y tratado de agua

#### Implicaciones SARA {.unnumbered .unlisted}

El resumen de las implicaciones para los contratos bajo regulación armonizada respecto las no SARA son:

- El anuncio deben publicarse en el Diario Oficial de la Unión Europea (en lugar del BOE).
- Plazos más largos y pasos adicionales que ralentizan el proceso.
- Rigidez en las modificaciones.

### Aprobación por Consejo de Ministros

El Consejo de Ministros debe aprobar el contrato cuando su importe supere los 12.000.000 €. Esto está definido en el art. 32.6.c del LCSP.

### Plazo de ejecución

El plazo de ejecución se especifica en el pliego, sin que exista un plazo máximo. Los plazos de ejecución se regulan en el art. 210 de la ley 9/2017.

### Prórrogas en concesiones

Las prórrogas de las concesiones deben ser acordadas entre la entidad contratante y el contratista.

Vienen reguladas en el art. 205 de la ley 9/2017.

### Procedimientos de adjudicación

Procedimientos o formas de adjudicación:

- Procedimiento abierto
- Procedimiento abierto simplificado
- Procedimiento abierto simplificado abreviado
- Procedimiento restringido
- Procedimiento de negociación
- Procedimiento negociado sin publicidad
- Contrato menor
- Diálogo competitivo
- Procedimiento de asociación para la innovación
- Contrato menor
- Contratación centralizada

La plataforma para realizar contratación es Conecta-Contratación.

[Página web de Conecta-Contratación](https://catalogocentralizado.hacienda.gob.es/pctw/Acceso/inicio.aspx).

Los contratos sujetos a contratación armonizada se llaman también contratos SARA.

Los tiempos para comenzar se reducen aproximadamente a la mitad en caso de tramitación urgente.

Sobre los tiempos para comenzar, habría que sumar el necesario para la preparación del contrato (redaccción de la Memoria Justificativa, Pliegos Técnicos y Administrativos, etc.).

#### Procedimiento abierto

Un procedimientos abierto se denomina así ya que cualquiera puede licitar al mismo.

Existen varios subtipos de procedimiento abierto:

- Procedimiento abierto (ordinario)
- Procedimiento abierto simplificado
- Procedimiento abierto simplificado abreviado

##### Procedimiento abierto (ordinario) {.unnumbered .unlisted}

El procedimiento abierto es el ordinario de contratación. Se le llama en este apartado procedimiento abierto ordinario para distinguirlo de variantes como el simplificado y el abreviado, aunque este no sea su nombre oficial.

El plazo de presentación de proposiciones es:

- En caso de regulación NO armonizada: 15 días
- En caso de regulación armonizada
  - En situación estándar: 35 días
  - Si se publicó un anuncio previo o en situación de emergencia: 15 días
  
Si se aceptan propuestas de ofertas por medios electrónicos, reducen los plazos en 5 días. Esto se define en el art. 156.3.c.

No tiene restricciones respecto al importe del contrato.

##### Procedimiento abierto simplificado {.unnumbered .unlisted}

El procedimiento abierto simplificado se regula en el art. 159 del LCSP.

Condiciones para su aplicación:

- Criterio económico
  - Para contratos de obras, valor estimado <= 2.000.000 €
  - Para contratos de suministro y de servicios, valor estimado <= 140.000 €
- Criterios de adjudicación
  - En prestación de carácter no intelectual, los juicios de valor deben ser <25%
  - En prestación intelectual, los juicios de valor deben ser <40%

**Plazo de presentación** de proposiciones mínimo:

- Obras: 20 días
- Otros: 15 días

El procedimiento abierto simplificado es incompatible con SARA, por ello los umbrales económicos del p.a.s. son los mismos que SARA y de hecho la ley los referencia directamente.

##### Procedimiento abierto simplificado abreviado {.unnumbered .unlisted}

Condiciones para su aplicación:

- Criterio económico
  - Para contratos de obras, valor estimado <= 80.000 €.
  - Para contratos de suministros y servicios, valor estimado <= 60.000 €
- Tipo de prestación
  - Solo prestación de carácter no intelectual

Plazo de presentación de proposiciones mínimo:

- Compras corrientes disponibles en el mercado: 5 días hábiles
- Otros: 10 días hábiles

No es necesaria la acreditación de la solvencia económica y financiera y técnica o profesional de los licitadores.

La oferta se entregará en un único sobre y se evaluará con arreglo a criterios de adjudicación cuantificables mediante la mera aplicación de fórmulas establecidas en los pliegos.

Con "sobre único" se refiere a que solo se hace una oferta con valores cuantificables y que, a diferencia de otros procesos, no hace falta emitir aparte la oferta con valores subjetivos o cualitativos.

#### Procedimiento restringido

Solo puede licitar quien pasa un filtro.

No permite negociaciones en el precio.

#### Procedimiento con negociación

Estos procedimientos permiten negociación, a diferencia del abierto y el restringido.

Existen dos tipos:

- Procedimiento con negociación [estándar]
- Procedimiento con negociación sin publicidad

##### Procedimiento con negociación estándar {.unnumbered .unlisted}

Viene recogido en el artículo 167 de la LCSP.

Permite negociar con los licitadores las condiciones, quedando fuera los aspectos esenciales y los criterios de adjudicación.

La versión estándar requiere publicidad.

Solo se puede aplicar en un número de casos:

- Cuando requiera que los licitadores realicen un trabajo previo de diseño o adaptación.
- Cuando se trate de una solución innovadoras
- Cuando las negociaciones sean ineludibles.
- Cuando el órgano de contratación con puede precisar suficientemente las especificaciones.
- Cuando no se haya recibido nada aceptable tras realizar un procedimiento abierto o restringido.
- Cuando se trate de contratos de servicios sociales personalísimos.

##### Procedimiento negociado sin publicidad {.unnumbered .unlisted}

Regulado en el artículo 168 del LCSP.

Es similar al procedimiento negociado estándar pero no requiere publicidad.

Requiere que se de una compleja lista de condiciones, entre ellas:

- No se haya presentado ninguna oferta; ninguna oferta adecuada; ninguna solicitud de participación; o ninguna solicitud de participación adecuada en respuesta a un procedimiento abierto o a un procedimiento restringido.
- Cuando las obras, los suministros o los servicios solo puedan ser encomendados a un empresario determinado.
- Cuando el contrato haya sido declarado

#### Diálogo competitivo

Comparte los supuestos del procedimiento negociado.

Supone mantener una mesa de diálogo.

Permite el pago de primas o compensaciones a los licitadores que se presenten.

#### Procedimiento de asociación para la innovación

Relacionado con la innovación.

#### Contrato menor

Un contrato menor debe cumplir una serie de condiciones.

Condiciones del contrato menor:

- Condiciones económicas
  - Contratos de obras: valor estimado < 40.000.
  - Contratos de suministros o servicios: valor estimado < 15.000 €.

En este caso se define también en valor estimado y no al importe base de licitación.

Se debe solicitar al menos 3 prespuestos.

No se requerirá la aprobación del gasto, pero sí la incorporación al expediente de la factura correspondiente.

Los contratos menores NO son susceptbiles de prórroga.

Según los apuntes de Andreu Bosa, lleva un mes su tramitación.

### (Paso 8) División en lotes

Está regulado en el artículo 99 del LCSP.

Es obligatorio realizar lotes. El mínimo de lotes es 2, y no hay máximo. Se suelen dividir por criterios funcionales o geográficos.

Si divides un gran contrato en lotes y la suma es SARA, la ley permite que algunos lotes pequeños (que no superen los 80.000 € en servicios/suministros o 1 millón en obras) se libren de la burocracia SARA, siempre que la suma de esos lotes "liberados" no supere el 20% del valor total del proyecto.

### Anuncios de licitaciones públicas

Los procedimientos negociados sin publicidad no se publican.

El resto de licitaciones se anuncian en la [Plataforma de Contratación del Sector Público](https://contrataciondelestado.es/).

Las licitación de organismos de la AGE se publican además en el Boletín Oficial del Estado.

Las licitaciones sujetas a regulación armonizada (SARA) se publica en el Diario Oficial de la Unión Europea.

### Procedimiento general de contratación TIC

Pasos técnicos:

1. Análisis de necesidades
2. Especificaciones ténico-funcionales
3. Evaluación y selección de ofertas
4. Validación y pruebas

Actividades del análisis de contratación:

1. Planificación de la capacidad del S.I.
2. Decisiones HW / SW
3. Decisiones sobre la rentabilidad económica

Estos tres puntos se desarrollan en los temas 2023.40, 2024.41 y 2024.42 de TIC, que no suelen entrar mucho.

Expediente de contratación:

- Memoria
- Certificado
- Pliegos
  - Pliego de Cláusulas Administrativas Particulares (PCAP).
  - Pliego de Prescripciones Técnicas (PPT).
- Informes preceptivos de la Memoria y de los Pliegos
  - Para el PCAP, lo realiza el servicio jurítico de la abogacía del estado
  - La memoria y el PPT lo realiza el SGAD
- Informe de fiscalización por la Intervención Delegada

El Pliego de Cláusulas Administrativas general (PCAG) consta de unas diapositivas.

El PCAP tiene carácter legal y contractual.


En la administración pública nunca se contratan personas. Se contratan solamente servicios y se necesitan personas para cubrir esos servicios.


En caso de retraso en la ejecución del contrato en proporción de 0,60 € por cada 1.000 €. En caso de que se supere el 5% del total se puede rescindir el contrato.


Hay un proceso de recepción de la inversión. En ella está involucrado un técnico gestor.

Corenet es una aplicación de la Intervención General de la Administración del Estado (IGAE) para revisar la recepción de contrato de más de 50.000 € a través de un interventaror de la IGAE. Suele ser un perfil TIC dentro de este organismo.
